import type { Track } from "@/lib/course";

/*
  Program narastający: jeden detal przewodni na ścieżkę.
  Każda linia ma `since` — lekcję, w której się pojawia. Lekcja pokazuje linie
  ze swojej i wcześniejszych lekcji; nowe są wyróżnione, stare mają dymek z przypomnieniem.

  Zapis w stylu Fanuc: wymiary z kropką dziesiętną (lekcja F1.1).
  Frezowanie: płytka 80 × 50 × 20, naroża R10, obróbka konturu frezem Ø10 na głębokość 5 mm.
  Do lekcji F4.2 program prowadzi środek freza, odsunięty od konturu o promień 5 mm
  (X−5, Y55, łuki R15). Od F4.2 — wymiary z rysunku i korekcja G41 D1.
*/

/** `until` — lekcja, od której linia znika (zastąpiona innym zapisem). */
export interface BuildLine { code: string; since: string; note: string; until?: string }

export const buildup: Record<Track, { title: string; lines: BuildLine[] }> = {
  frezowanie: {
    title: "Płytka 80 × 50",
    lines: [
      { code: "O1000 (PLYTKA 80X50X20 - GCAT)", since: "F1.1", note: "Numer programu i nazwa detalu w komentarzu." },
      { code: "(ZERO W: LEWY DOLNY NAROZNIK, Z0 NA GORZE)", since: "F0.1", note: "Gdzie leży zero detalu. Wszystkie współrzędne niżej liczymy od tego punktu." },
      { code: "(P1 X0 Y0 / P2 X80 Y0 / P3 X80 Y50 / P4 X0 Y50)", since: "F0.1", note: "Naroża płytki odczytane z rysunku, względem zera W." },
      { code: "G21 G90 G17", since: "F1.4", note: "Milimetry, wymiary absolutne, płaszczyzna XY." },
      { code: "G40 G49 G80", since: "F1.5", note: "Kasowanie korekcji promienia, korekcji długości i cyklu — na wypadek, gdyby zostały z poprzedniego programu." },
      { code: "G54", since: "F0.3", note: "Aktywne przesunięcie zera detalu z rejestru G54." },
      { code: "(NADDATEK 1 MM NA GORNEJ POWIERZCHNI)", since: "F6.1", note: "Surówka jest o 1 mm wyższa — pierwsza operacja zbiera go do Z0." },
      { code: "T5 M06 (GLOWICA FI63 5Z 45ST)", since: "F6.1", note: "Pierwsza operacja: planowanie górnej powierzchni głowicą Ø63." },
      { code: "G43 H5 Z50.", since: "F6.1", note: "Korekcja długości głowicy." },
      { code: "S1000 M03", since: "F6.1", note: "vc ≈ 200 m/min dla Ø63." },
      { code: "M08", since: "F6.1", note: "Chłodziwo." },
      { code: "G00 X-40. Y25.", since: "F6.1", note: "Start poza detalem: promień głowicy 31,5 + zapas." },
      { code: "G00 Z5.", since: "F6.1", note: "Zjazd nad powierzchnię." },
      { code: "G01 Z0. F200", since: "F6.1", note: "Zejście na wymiar obok detalu." },
      { code: "G01 X120. F800", since: "F6.1", note: "Jedno przejście: ae = 50 z 63 mm (79%). fz = 800 / (5 · 1000) = 0,16." },
      { code: "G00 Z50.", since: "F6.1", note: "Odjazd." },
      { code: "M09", since: "F6.1", note: "Chłodziwo wyłączone." },
      { code: "M05", since: "F6.1", note: "Stop wrzeciona przed wymianą na frez." },
      { code: "T1 M06 (FREZ FI10)", since: "F2.1", note: "Wymiana na narzędzie nr 1 — frez Ø10." },
      { code: "G43 H1 Z50.", since: "F4.1", note: "Włączenie korekcji długości narzędzia nr 1 i dojazd na Z50." },
      { code: "S2500 M03", since: "F2.2", note: "2500 obr/min, obroty w prawo." },
      { code: "M08", since: "F2.4", note: "Chłodziwo włączone przed dojazdem do detalu." },
      { code: "G00 X-20. Y10.", since: "F3.1", note: "Ruch szybki nad punkt startu, z boku detalu." },
      { code: "G00 Z5.", since: "F3.1", note: "Zjazd szybki na wysokość bezpieczną 5 mm nad górną powierzchnią." },
      { code: "G01 Z-5. F150", since: "F3.2", note: "Wejście na głębokość obok detalu, posuw 150 mm/min." },
      { code: "G01 X-5. F400", since: "F3.2", until: "F4.2", note: "Dojazd do lewej krawędzi (środek freza 5 mm od konturu)." },
      { code: "G41 D1 G01 X0. F400", since: "F4.2", until: "F4.3", note: "Włączenie korekcji promienia z rejestru D1 na dojeździe. Od teraz program opisuje kontur detalu." },
      { code: "G41 D1 G01 X-10. Y0. F400", since: "F4.3", note: "Korekcja promienia włączana na odcinku w powietrzu, przed łukiem najazdu." },
      { code: "G03 X0. Y10. R10.", since: "F4.3", note: "Łuk najazdu stycznego — frez wchodzi na kontur bez zatrzymania na ścianie." },
      { code: "G01 Y55.", since: "F3.2", until: "F3.3", note: "Lewa krawędź w górę, do narożnika toru — kontur bez zaokrągleń." },
      { code: "G01 X85.", since: "F3.2", until: "F3.3", note: "Górna krawędź." },
      { code: "G01 Y-5.", since: "F3.2", until: "F3.3", note: "Prawa krawędź w dół." },
      { code: "G01 X-5.", since: "F3.2", until: "F3.3", note: "Dolna krawędź." },
      { code: "G01 Y10.", since: "F3.2", until: "F3.3", note: "Domknięcie konturu. Od lekcji F3.3 naroża dostaną promień R10." },
      { code: "G01 Y40.", since: "F3.3", note: "Lewa krawędź w górę, do początku naroża." },
      { code: "G02 X10. Y55. R15.", since: "F3.3", until: "F4.2", note: "Naroże R10 + promień freza 5 = tor R15." },
      { code: "G02 X10. Y50. R10.", since: "F4.2", note: "Naroże z rysunku: R10. Promień freza dolicza korekcja." },
      { code: "G01 X70.", since: "F3.3", note: "Górna krawędź." },
      { code: "G02 X85. Y40. R15.", since: "F3.3", until: "F4.2", note: "Prawe górne naroże." },
      { code: "G02 X80. Y40. R10.", since: "F4.2", note: "Prawe górne naroże, wymiar z rysunku." },
      { code: "G01 Y10.", since: "F3.3", note: "Prawa krawędź w dół." },
      { code: "G02 X70. Y-5. R15.", since: "F3.3", until: "F4.2", note: "Prawe dolne naroże." },
      { code: "G02 X70. Y0. R10.", since: "F4.2", note: "Prawe dolne naroże, wymiar z rysunku." },
      { code: "G01 X10.", since: "F3.3", note: "Dolna krawędź." },
      { code: "G02 X-5. Y10. R15.", since: "F3.3", until: "F4.2", note: "Lewe dolne naroże — kontur zamknięty." },
      { code: "G02 X0. Y10. R10.", since: "F4.2", note: "Lewe dolne naroże — kontur zamknięty w punkcie wejścia." },
      { code: "G40 G01 X-20.", since: "F4.2", until: "F4.3", note: "Wyłączenie korekcji na odjeździe od konturu." },
      { code: "G03 X-10. Y20. R10.", since: "F4.3", note: "Łuk odjazdu stycznego." },
      { code: "G40 G01 X-20. Y10.", since: "F4.3", note: "Wyłączenie korekcji na odcinku w powietrzu." },
      { code: "G00 Z5.", since: "F3.1", note: "Odjazd w górę ruchem szybkim." },
      { code: "(KIESZEN 26X20 R6 GL.4, SRODEK X30 Y25)", since: "F6.2", note: "Kieszeń prostokątna tym samym frezem Ø10 — bez wymiany narzędzia." },
      { code: "G00 X23. Y25.", since: "F6.2", note: "Nad początek rampy, na osi kieszeni." },
      { code: "G01 Z0. F200", since: "F6.2", note: "Dojazd do powierzchni." },
      { code: "G01 X37. Z-1.", since: "F6.2", note: "Rampa: 1 mm na 14 mm drogi, około 4°." },
      { code: "X23. Z-2.", since: "F6.2", note: "Rampa w drugą stronę." },
      { code: "X37. Z-3.", since: "F6.2", note: "Rampa." },
      { code: "X23. Z-4.", since: "F6.2", note: "Rampa do pełnej głębokości." },
      { code: "X37. F400", since: "F6.2", note: "Wyrównanie dna na osi kieszeni." },
      { code: "Y29.", since: "F6.2", note: "Pętla zgrubna, 1 mm od ścian, przeciwnie do zegara." },
      { code: "X23.", since: "F6.2", note: "Pętla zgrubna." },
      { code: "Y21.", since: "F6.2", note: "Pętla zgrubna." },
      { code: "X37.", since: "F6.2", note: "Pętla zgrubna." },
      { code: "Y25.", since: "F6.2", note: "Powrót na oś kieszeni." },
      { code: "G41 D1 G01 X24. Y21.", since: "F6.2", note: "Włączenie korekcji przed łukiem najazdu." },
      { code: "G03 X30. Y15. R6.", since: "F6.2", note: "Najazd styczny na dolną ścianę." },
      { code: "G01 X37.", since: "F6.2", note: "Ściana dolna — obieg przeciwnie do zegara to frezowanie współbieżne w kieszeni." },
      { code: "G03 X43. Y21. R6.", since: "F6.2", note: "Naroże R6 — większe niż promień freza 5." },
      { code: "G01 Y29.", since: "F6.2", note: "Ściana prawa." },
      { code: "G03 X37. Y35. R6.", since: "F6.2", note: "Naroże." },
      { code: "G01 X23.", since: "F6.2", note: "Ściana górna." },
      { code: "G03 X17. Y29. R6.", since: "F6.2", note: "Naroże." },
      { code: "G01 Y21.", since: "F6.2", note: "Ściana lewa." },
      { code: "G03 X23. Y15. R6.", since: "F6.2", note: "Naroże." },
      { code: "G01 X30.", since: "F6.2", note: "Domknięcie ściany dolnej." },
      { code: "G03 X36. Y21. R6.", since: "F6.2", note: "Odjazd styczny." },
      { code: "G40 G01 X30. Y25.", since: "F6.2", note: "Wyłączenie korekcji na środku kieszeni." },
      { code: "G00 Z5.", since: "F6.2", note: "Odjazd nad detal." },
      { code: "(KIESZEN OKRAGLA FI20 GL.4, SRODEK X60 Y25)", since: "F6.3", note: "Kieszeń okrągła, znowu tym samym frezem." },
      { code: "G00 X63. Y25.", since: "F6.3", note: "Start spirali: 3 mm od środka kieszeni." },
      { code: "G01 Z0. F200", since: "F6.3", note: "Dojazd do powierzchni." },
      { code: "G03 I-3. Z-1.", since: "F6.3", until: "F7.1", note: "Spirala: pełny obrót wokół X60 Y25 i 1 mm w dół." },
      { code: "G03 I-3. Z-2.", since: "F6.3", until: "F7.1", note: "Spirala." },
      { code: "G03 I-3. Z-3.", since: "F6.3", until: "F7.1", note: "Spirala." },
      { code: "G03 I-3. Z-4.", since: "F6.3", until: "F7.1", note: "Spirala do pełnej głębokości." },
      { code: "M98 P2000 L4", since: "F7.1", note: "Cztery zwoje spirali: podprogram O2000 wykonany 4 razy." },
      { code: "G03 I-3. F400", since: "F6.3", note: "Obrót na dnie — wyrównanie dna." },
      { code: "G41 D1 G01 Y18.", since: "F6.3", note: "Włączenie korekcji: 7 mm odcinka w dół." },
      { code: "G03 X70. Y25. R7.", since: "F6.3", note: "Najazd styczny na ścianę Ø20." },
      { code: "G03 I-10.", since: "F6.3", note: "Pełny okrąg wykańczający po ścianie." },
      { code: "G03 X63. Y32. R7.", since: "F6.3", note: "Odjazd styczny." },
      { code: "G40 G01 Y25.", since: "F6.3", note: "Wyłączenie korekcji." },
      { code: "G00 Z5.", since: "F6.3", note: "Odjazd nad detal." },
      { code: "M09", since: "F2.4", note: "Chłodziwo wyłączone po obróbce." },
      { code: "M05", since: "F2.2", note: "Stop wrzeciona." },
      { code: "T2 M06 (NAWIERTAK FI10 90ST)", since: "F5.1", note: "Druga operacja: nawiercenie czterech otworów." },
      { code: "G43 H2 Z50.", since: "F5.1", note: "Korekcja długości nawiertaka. Z50 to poziom początkowy cyklu." },
      { code: "S1900 M03", since: "F5.1", note: "vc ≈ 60 m/min dla Ø10." },
      { code: "M08", since: "F5.1", note: "Chłodziwo." },
      { code: "G82 X10. Y10. Z-3. R2. P200 F150", since: "F5.1", until: "F5.4", note: "Nawiercenie z postojem 0,2 s na dnie. Fazka Ø6 pod gwint M6." },
      { code: "G99 G82 X10. Y10. Z-3. R2. P200 F150", since: "F5.4", note: "Nawiercenie z postojem 0,2 s. G99 — między otworami powrót tylko do R2." },
      { code: "X70.", since: "F5.1", note: "Cykl modalny: sam ruch w X to kolejny otwór." },
      { code: "Y40.", since: "F5.1", note: "Trzeci otwór." },
      { code: "X10.", since: "F5.1", note: "Czwarty otwór." },
      { code: "G80", since: "F5.1", note: "Koniec cyklu." },
      { code: "M09", since: "F5.1", note: "Chłodziwo wyłączone przed wymianą." },
      { code: "M05", since: "F5.1", note: "Stop wrzeciona przed wymianą." },
      { code: "T3 M06 (WIERTLO FI5 VHM 140ST)", since: "F5.2", note: "Trzecia operacja: otwory pod gwint M6." },
      { code: "G43 H3 Z50.", since: "F5.2", note: "Korekcja długości wiertła." },
      { code: "S3800 M03", since: "F5.2", note: "vc ≈ 60 m/min dla Ø5." },
      { code: "M08", since: "F5.2", note: "Chłodziwo." },
      { code: "G83 X10. Y10. Z-16. R2. Q4. F380", since: "F5.2", until: "F5.4", note: "Wiercenie z wycofaniem co 4 mm na głębokość 16 mm (3,2 × D)." },
      { code: "G99 G83 X10. Y10. Z-16. R2. Q4. F380", since: "F5.4", note: "Wiercenie z wycofaniem co 4 mm, powrót do R2 między otworami." },
      { code: "X70.", since: "F5.2", note: "Drugi otwór." },
      { code: "Y40.", since: "F5.2", note: "Trzeci otwór." },
      { code: "X10.", since: "F5.2", note: "Czwarty otwór." },
      { code: "G80", since: "F5.2", note: "Koniec cyklu." },
      { code: "M09", since: "F5.2", note: "Chłodziwo wyłączone." },
      { code: "M05", since: "F5.2", note: "Stop wrzeciona." },
      { code: "T4 M06 (GWINTOWNIK M6X1)", since: "F5.3", note: "Czwarta operacja: gwinty M6×1." },
      { code: "G43 H4 Z50.", since: "F5.3", note: "Korekcja długości gwintownika." },
      { code: "S500 M03", since: "F5.3", note: "Obroty gwintowania." },
      { code: "M29 S500", since: "F5.3", note: "Fanuc: tryb gwintowania sztywnego — wrzeciono sprzężone z osią Z." },
      { code: "M08", since: "F5.3", note: "Chłodziwo." },
      { code: "G84 X10. Y10. Z-12. R5. F500", since: "F5.3", until: "F5.4", note: "Gwintowanie na 12 mm. F = S · P = 500 · 1." },
      { code: "G99 G84 X10. Y10. Z-12. R5. F500", since: "F5.4", note: "Gwintowanie na 12 mm, F = 500 · 1, powrót do R5 między otworami." },
      { code: "X70.", since: "F5.3", note: "Drugi gwint." },
      { code: "Y40.", since: "F5.3", note: "Trzeci gwint." },
      { code: "X10.", since: "F5.3", note: "Czwarty gwint." },
      { code: "G80", since: "F5.3", note: "Koniec cyklu gwintowania." },
      { code: "M09", since: "F5.3", note: "Chłodziwo wyłączone." },
      { code: "M05", since: "F5.3", note: "Stop wrzeciona." },
      { code: "G91 G28 Z0.", since: "F0.2", note: "Odjazd osi Z do punktu referencyjnego R (Fanuc). G91 to wymiary przyrostowe — poznasz je w F1.3." },
      { code: "G90", since: "F1.3", note: "Powrót do wymiarów absolutnych po G91." },
      { code: "M30", since: "F1.5", note: "Koniec programu i powrót na początek." },
      { code: "O2000 (ZWOJ SPIRALI 1 MM)", since: "F7.1", note: "Podprogram: w pamięci sterowania osobny program, w symulatorze zapisany pod M30." },
      { code: "G91 G03 I-3. Z-1.", since: "F7.1", note: "Jeden zwój spirali przyrostowo: pełny obrót i 1 mm w dół od miejsca, w którym frez stoi." },
      { code: "G90", since: "F7.1", note: "Przywrócenie wymiarów absolutnych przed powrotem — G91 jest modalne." },
      { code: "M99", since: "F7.1", note: "Koniec podprogramu, powrót do bloku po M98." },
    ],
  },
  toczenie: {
    title: "Wałek stopniowany",
    lines: [
      { code: "O2001 (WALEK STOPNIOWANY - GCAT)", since: "T1.1", note: "Numer programu i nazwa detalu." },
      { code: "(ZERO W: OS OBROTU, CZOLO DETALU)", since: "T0.1", note: "X0 na osi obrotu, Z0 na czole gotowego detalu. Wszystko w stronę uchwytu ma Z ujemne." },
      { code: "(SUROWKA: PRET FI40, WYSIEG 70)", since: "T0.1", note: "Pręt Ø40 wystaje 70 mm z uchwytu." },
      { code: "(KONTUR: X18 Z0 / X20 Z-1 / X20 Z-20 / X28 Z-20)", since: "T0.2", note: "Punkty konturu w średnicach: faza, czop Ø20, stopień." },
      { code: "(X30 Z-21 / X30 Z-40 / X36 Z-40 / X36 Z-55)", since: "T0.2", note: "Dalsza część konturu: faza, Ø30, stopień, Ø36." },
      { code: "G18 G21 G40 G80 G99", since: "T1.3", note: "Blok startowy tokarki: płaszczyzna ZX, milimetry, bez korekcji ostrza i cykli, posuw w mm/obr." },
      { code: "G54", since: "T0.3", note: "Przesunięcie zera w Z na czoło detalu, zmierzone dotknięciem noża." },
      { code: "T0101 (NOZ ZEWN. CNMG R0.8)", since: "T2.1", note: "Nóż z pozycji 1 z korekcją 1. Głowica obraca się od razu — nóż stoi w punkcie referencyjnym, z dala od detalu." },
      { code: "G50 S3000", since: "T2.2", note: "Limit obrotów przy stałej prędkości skrawania." },
      { code: "G96 S200 M03", since: "T2.2", note: "Stała prędkość skrawania 200 m/min, obroty w prawo." },
      { code: "M08", since: "T2.3", note: "Chłodziwo." },
      { code: "(PLANOWANIE CZOLA)", since: "T2.3", note: "Pierwsze skrawanie wałka." },
      { code: "G00 X44. Z0.", since: "T2.3", note: "Dojazd na wysokość czoła, poza średnicą pręta." },
      { code: "G01 X-1.6 F0.15", since: "T2.3", note: "Planowanie przez oś: X = −2 · rε, żeby nie zostawić pipki. Posuw 0,15 mm/obr." },
      { code: "G00 Z2.", since: "T2.3", note: "Odjazd od czoła." },
      { code: "(TOCZENIE ZGRUBNE - RECZNIE, NADDATEK 0.4 NA SREDNICY)", since: "T3.1", note: "Przejścia zgrubne zapisane blok po bloku. W module T5 zastąpi je jeden cykl G71." },
      { code: "G00 X36.4", since: "T3.1", note: "Ruch szybki na średnicę przejścia, przed czołem (Z2)." },
      { code: "G01 Z-54.8 F0.3", since: "T3.1", note: "Toczenie wzdłużne na Ø36,4. Zostaje 0,2 mm na stronę i 0,2 mm w Z na wykończenie." },
      { code: "X40.5", since: "T3.1", note: "Wyjście promieniowe z materiału, nadal posuwem." },
      { code: "G00 Z2.", since: "T3.1", note: "Powrót ruchem szybkim nad czoło — nóż jest już ponad detalem." },
      { code: "G00 X32.", since: "T3.2", note: "Drugie przejście: Ø32, ap = 2,2." },
      { code: "G01 Z-39.8", since: "T3.2", note: "Do stopnia Ø36 z naddatkiem 0,2." },
      { code: "X37.", since: "T3.2", note: "Wyjście." },
      { code: "G00 Z2.", since: "T3.2", note: "Powrót." },
      { code: "G00 X30.4", since: "T3.2", note: "Trzecie przejście: Ø30,4." },
      { code: "G01 Z-39.8", since: "T3.2", note: "Do stopnia." },
      { code: "X33.", since: "T3.2", note: "Wyjście." },
      { code: "G00 Z2.", since: "T3.2", note: "Powrót." },
      { code: "G00 X25.5", since: "T3.2", note: "Czwarte przejście: Ø25,5." },
      { code: "G01 Z-19.8", since: "T3.2", note: "Do stopnia Ø30." },
      { code: "X31.", since: "T3.2", note: "Wyjście." },
      { code: "G00 Z2.", since: "T3.2", note: "Powrót." },
      { code: "G00 X20.4", since: "T3.2", note: "Piąte przejście: Ø20,4." },
      { code: "G01 Z-19.8", since: "T3.2", note: "Do stopnia." },
      { code: "X26.5", since: "T3.2", note: "Wyjście." },
      { code: "G00 Z2.", since: "T3.2", note: "Powrót." },
      { code: "G28 U0.", since: "T3.2", note: "Odjazd do zmiany noża: najpierw X." },
      { code: "G28 W0.", since: "T3.2", note: "Potem Z." },
      { code: "T0202 (NOZ WYKANCZAJACY VBMT R0.4)", since: "T3.2", note: "Nóż wykańczający z mniejszym narożem — lepsza powierzchnia." },
      { code: "(T0202: R0.4, KIERUNEK OSTRZA 3)", since: "T4.2", note: "W tabeli korekcji noża 2: promień naroża 0,4 i kierunek ostrza 3 — bez nich G42 nie ma czego liczyć." },
      { code: "G96 S250 M03", since: "T3.2", note: "Wyższa prędkość skrawania na wykończenie." },
      { code: "(KONTUR WYKANCZAJACY)", since: "T3.2", note: "Kontur z rysunku, jednym przejściem." },
      { code: "G00 X14. Z2.", since: "T3.2", until: "T4.1", note: "Start na przedłużeniu linii fazy — nóż wchodzi na fazę po jej kierunku." },
      { code: "G42 G00 X14. Z2.", since: "T4.1", note: "Włączenie korekcji promienia ostrza na dojeździe. Nóż zewnętrzny w stronę uchwytu — materiał po lewej, nóż po prawej: G42." },
      { code: "G01 X20. Z-1. F0.1", since: "T3.2", note: "Faza 1 × 45° na czopie Ø20." },
      { code: "Z-20.", since: "T3.2", note: "Czop Ø20." },
      { code: "X28.", since: "T3.2", note: "Czoło stopnia do początku fazy." },
      { code: "X30. Z-21.", since: "T3.2", note: "Faza 1 × 45° na Ø30." },
      { code: "Z-40.", since: "T3.2", until: "T3.3", note: "Ø30 do stopnia — na razie z ostrym narożem." },
      { code: "X36.", since: "T3.2", until: "T3.3", note: "Czoło stopnia Ø36." },
      { code: "Z-55.", since: "T3.2", until: "T3.3", note: "Ø36." },
      { code: "Z-39.", since: "T3.3", note: "Ø30 do początku zaokrąglenia R1 w narożu wklęsłym." },
      { code: "G02 X32. Z-40. R1.", since: "T3.3", note: "Promień R1 w narożu wklęsłym — łuk zgodnie z zegarem przy X w górę." },
      { code: "G01 X35.", since: "T3.3", note: "Czoło stopnia." },
      { code: "G03 X36. Z-40.5 R0.5", since: "T3.3", note: "Zaokrąglenie krawędzi R0,5 — naroże wypukłe, łuk przeciwnie do zegara." },
      { code: "G01 Z-55.", since: "T3.3", note: "Ø36 — G01 trzeba podać znowu, bo po G03 obowiązywałby łuk." },
      { code: "X42.", since: "T3.2", note: "Wyjście po czole pręta." },
      { code: "G00 Z2.", since: "T3.2", until: "T4.1", note: "Odjazd." },
      { code: "G40 G00 Z2.", since: "T4.1", note: "Wyłączenie korekcji na odjeździe od detalu." },
      { code: "M09", since: "T2.3", note: "Chłodziwo wyłączone." },
      { code: "M05", since: "T2.2", note: "Stop wrzeciona." },
      { code: "G28 U0.", since: "T1.2", note: "Odjazd do punktu referencyjnego najpierw w X — przyrost U0 znaczy: bez ruchu pośredniego." },
      { code: "G28 W0.", since: "T1.2", note: "Potem w Z. Kolejność X, potem Z odsuwa nóż od detalu, zanim pojedzie wzdłuż osi." },
      { code: "M30", since: "T1.3", note: "Koniec programu." },
    ],
  },
};
