import type { Block } from "@/lib/article";

export const part2: Record<string, Block[]> = {
  "g40-g42": [
    { t: "p", x: "**Kompensacja promienia narzędzia** pozwala programować **kontur gotowego detalu**, a nie tor środka freza. Sterownik sam odsuwa narzędzie o wartość promienia zapisaną w rejestrze korekcji, dzięki czemu ten sam program działa po wymianie freza ⌀10 na ⌀12 albo po jego przeszlifowaniu." },
    { t: "h", x: "Po której stronie konturu" },
    { t: "p", x: "Reguła jest jedna i zawsze ta sama: **stań za narzędziem i patrz w kierunku jego ruchu**. Jeżeli narzędzie ma być po lewej stronie konturu, użyj **G41**; jeżeli po prawej — **G42**. **G40** kompensację wyłącza." },
    { t: "diagram", id: "g40-g42" },
    { t: "note", kind: "info", x: "Przy standardowych obrotach w prawo (M03) i frezowaniu konturu zewnętrznego, **G41 daje frezowanie współbieżne**, a G42 — przeciwbieżne. Współbieżne jest korzystniejsze na maszynach ze śrubą kulową: wiór jest grubszy na początku, cieńszy na końcu, przez co narzędzie mniej się grzeje i powierzchnia wychodzi lepsza." },
    { t: "h", x: "Składnia i rejestr korekcji" },
    { t: "code", x: "G41 D1 X_ Y_ F_        (włączenie, narzędzie z lewej)\n...bloki konturu...\nG40 X_ Y_              (wyłączenie)", caption: "Adres D wskazuje numer rejestru, w którym wpisany jest promień narzędzia." },
    { t: "table", head: ["Kod", "Działanie"], rows: [
      ["**G40**", "Wyłączenie kompensacji — tor wraca do zaprogramowanych współrzędnych"],
      ["**G41**", "Kompensacja z lewej strony konturu, patrząc w kierunku ruchu"],
      ["**G42**", "Kompensacja z prawej strony konturu"],
      ["**D**", "Numer rejestru z promieniem narzędzia (Fanuc). W Sinumerik korektor wynika z `T_ D_`"],
    ] },
    { t: "p", x: "W rejestrze wpisuje się zwykle **promień** narzędzia (Fanuc: kolumna „radius”), czasem jego **średnicę** — zależnie od ustawienia sterownika. Dodatkowa kolumna „wear” pozwala dostroić wymiar detalu bez zmiany programu: jeżeli zmierzona ścianka jest o 0,04 mm za gruba, wpisujesz −0,02 w zużycie promienia." },
    { t: "h", x: "Blok dojazdowy — najważniejsza część" },
    { t: "p", x: "Kompensacji nie da się włączyć w miejscu. Sterownik potrzebuje **ruchu prostoliniowego**, w trakcie którego przesunie narzędzie z pozycji nieskompensowanej na tor odsunięty o promień. Ten ruch nazywa się blokiem dojazdowym." },
    { t: "ul", items: [
      "Blok dojazdowy musi być **G00 lub G01** — nigdy G02/G03.",
      "Jego długość musi być **większa niż promień narzędzia**, najlepiej co najmniej 1,5-krotnie.",
      "Ruch powinien prowadzić **z zewnątrz materiału** w stronę punktu startu konturu.",
      "Wyłączenie G40 również wymaga ruchu — zwykle odjazdu na zewnątrz.",
    ] },
    { t: "sim", src: "G21 G90 G17 G54 G40\nS2200 M03\nG00 X-20 Y-20 Z5\nG01 Z-3 F100\nG41 D1 X0 Y0 F350\nG01 Y40\nG01 X60\nG01 Y0\nG01 X0\nG40 X-20 Y-20\nG00 Z5\nM30", caption: "Kompensacja włączana w dojeździe z punktu (−20, −20) do początku konturu i wyłączana w odjeździe do tego samego punktu. Symulator pokazuje tor programowany — na maszynie tor rzeczywisty będzie odsunięty o promień freza." },
    { t: "h", x: "Wejście styczne — wariant zalecany" },
    { t: "p", x: "Dojazd prostopadły do konturu zostawia na powierzchni ślad wejścia. Lepszym rozwiązaniem jest dojazd prostoliniowy z włączeniem kompensacji, a potem **wejście po łuku stycznym** do konturu." },
    { t: "sim", src: "G21 G90 G17 G54 G40\nS2400 M03\nG00 X-25 Y10 Z5\nG01 Z-3 F100\nG41 D1 X-10 Y0 F350\nG03 X0 Y10 R10\nG01 Y40\nG01 X60\nG01 Y0\nG01 X0\nG03 X-10 Y20 R10\nG40 G01 X-25 Y10\nG00 Z5\nM30", caption: "Łuk R10 wprowadza narzędzie stycznie do ścianki — bez uskoku na powierzchni." },
    { t: "h", x: "Ograniczenia geometryczne" },
    { t: "ul", items: [
      "**Łuk wewnętrzny mniejszy od promienia narzędzia** — niewykonalny. Frez ⌀12 nie zrobi naroża R4.",
      "**Rowek węższy niż średnica narzędzia** — sterownik zgłosi przecięcie toru.",
      "**Zbyt krótki odcinek konturu** (krótszy niż średnica narzędzia) przy zmianie kierunku — może wystąpić podcięcie.",
      "**Zmiana kierunku kompensacji** (G41 → G42) bez wyłączenia przez G40 — zachowanie zależne od sterownika, lepiej tego unikać.",
    ] },
    { t: "note", kind: "tip", x: "Zanim uruchomisz program z kompensacją, wpisz do rejestru **wartość zerową** i przejedź program na sucho. Tor pokryje się wtedy z zaprogramowanym konturem, co pozwala sprawdzić samą geometrię. Dopiero potem wprowadź rzeczywisty promień." },
    { t: "h", x: "Fanuc kontra Sinumerik" },
    { t: "table", head: ["Zagadnienie", "Fanuc", "Sinumerik"], rows: [
      ["Włączenie", "`G41 D1`", "`G41` (korektor z `T1 D1`)"],
      ["Rejestr", "Osobne kolumny promienia i zużycia", "Parametry narzędzia w tabeli, pole `$TC_DP6`"],
      ["Dojazd", "Prostoliniowy", "Prostoliniowy; dodatkowo `NORM`, `KONT`, `KONTC`, `KONTT` sterują sposobem najazdu"],
      ["Naroża zewnętrzne", "Domknięcie łukiem lub przecięciem, zależnie od parametru", "`G450` — łuk, `G451` — przecięcie torów"],
    ] },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Włączenie kompensacji w bloku z łukiem** — alarm.",
      "**Blok dojazdowy krótszy niż promień** — alarm o przecięciu toru albo podcięcie.",
      "**Zapomniane G40** przed wymianą narzędzia — kolejne narzędzie pracuje z korekcją poprzedniego.",
      "**Pomylenie D z H** — H to rejestr długości, D promienia. Wpisanie długości narzędzia jako promienia daje tor odsunięty o kilkadziesiąt milimetrów.",
      "**Zły dobór strony** — G41 zamiast G42 przy konturze zewnętrznym skutkuje detalem mniejszym o średnicę narzędzia zamiast większym.",
    ] },
  ],

  "g43-g49": [
    { t: "p", x: "**G43** aktywuje **korekcję długości narzędzia**: sterownik dodaje do współrzędnej Z wartość zapisaną w rejestrze wskazanym adresem **H**. Dzięki temu program pisze się względem zera detalu, niezależnie od tego, jak długo wystaje aktualne narzędzie z uchwytu." },
    { t: "h", x: "Skąd bierze się wartość H" },
    { t: "p", x: "Długość narzędzia mierzy się jedną z trzech metod:" },
    { t: "ul", items: [
      "**Dotykiem na detalu** — narzędzie sprowadza się na powierzchnię przez papier lub czujnik, a odczytaną pozycję maszynową wpisuje do rejestru. Najprostsze, ale wymaga powtórzenia dla każdego detalu.",
      "**Przedustawiaczem** — długość mierzy się poza maszyną, wpisuje do rejestru raz na cały okres życia narzędzia w uchwycie.",
      "**Sondą narzędziową na stole** — pomiar automatyczny, najbardziej powtarzalny; wynik trafia do rejestru bez udziału operatora.",
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "T2 M06\nG43 H2 Z50 M03 S2000     (aktywacja przy pierwszym dojeździe w Z)\n...obróbka...\nG49                       (dezaktywacja, opcjonalna przed wymianą)" },
    { t: "table", head: ["Kod", "Działanie"], rows: [
      ["**G43**", "Dodaje wartość z rejestru H do pozycji Z (kompensacja dodatnia — standard)"],
      ["**G44**", "Odejmuje wartość z rejestru; stosowane rzadko, w specyficznych konfiguracjach"],
      ["**G49**", "Wyłącza korekcję długości"],
      ["**H**", "Numer rejestru długości"],
    ] },
    { t: "note", kind: "warn", x: "**Numer H powinien odpowiadać numerowi narzędzia.** Praktyka „T5 → H5” jest tak powszechna, że część sterowników potrafi ją wymusić parametrem. Aktywowanie H3 przy narzędziu T5 oznacza, że maszyna liczy pozycję Z dla zupełnie innej długości — jeśli narzędzie jest dłuższe niż zakłada rejestr, wbija się w detal albo w stół." },
    { t: "h", x: "Aktywacja musi zawierać ruch w Z" },
    { t: "p", x: "Sam blok `G43 H2` bez współrzędnej Z na wielu sterownikach niczego nie zmienia aż do następnego ruchu w tej osi — a wtedy narzędzie „przeskakuje” o całą długość korekcji. Dlatego G43 pisze się razem z dojazdem na wysokość bezpieczną, na przykład `G43 H2 Z50`. Ruch ten wykonuje się z pełną prędkością szybką, więc wysokość musi być rzeczywiście bezpieczna." },
    { t: "sim", src: "G21 G90 G17 G54 G40 G49 G80\nT2 M06\nG43 H2 Z50\nS2000 M03\nG00 X20 Y20\nG00 Z2\nM08\nG01 Z-4 F120\nG01 X70 F400\nG01 Y50\nG00 Z50\nM09\nM05\nM30", caption: "Kompletny szkielet obróbki jednym narzędziem. Symulator nie odwzorowuje przesunięcia z rejestru — pokazuje tor programowany." },
    { t: "h", x: "Sinumerik — inaczej" },
    { t: "p", x: "Sinumerik **nie ma funkcji G43**. Długość narzędzia aktywuje się przez samo wywołanie narzędzia i numeru ostrza: `T1 D1`. Każde narzędzie ma w tabeli komplet parametrów: długości w trzech osiach, promień, typ. Wywołanie `D0` dezaktywuje wszystkie korekcje — to odpowiednik G49." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Rozjazd numeru H i T** — najczęstsza przyczyna uderzenia narzędzia w stół.",
      "**Brak G43 po wymianie narzędzia** — maszyna liczy Z od czoła wrzeciona.",
      "**Zmierzona długość przy innym wysięgu** — przekładając narzędzie w uchwycie, trzeba zmierzyć je ponownie.",
      "**Pozostawione G43 dla poprzedniego narzędzia** — dlatego blok bezpiecznego startu zawiera G49.",
    ] },
  ],

  "g90-g91": [
    { t: "p", x: "Funkcje **G90** i **G91** decydują, jak sterownik interpretuje liczby przy adresach osi. W trybie **absolutnym (G90)** każda współrzędna jest adresem względem **zera detalu**. W trybie **przyrostowym (G91)** — przesunięciem względem **aktualnego położenia narzędzia**." },
    { t: "diagram", id: "g90-g91" },
    { t: "h", x: "Ten sam blok, dwa różne miejsca" },
    { t: "p", x: "Narzędzie stoi w punkcie X20 Y10. Blok `G01 X30 Y20` oznacza:" },
    { t: "ul", items: [
      "w trybie **G90** — jedź do punktu o współrzędnych (30, 20),",
      "w trybie **G91** — przesuń się o 30 mm w X i 20 mm w Y, czyli do punktu (50, 30).",
    ] },
    { t: "h", x: "Kiedy który tryb" },
    { t: "table", head: ["Zastosowanie", "Tryb", "Uzasadnienie"], rows: [
      ["Kontur z rysunku z wymiarami od bazy", "G90", "Współrzędne przepisuje się wprost z rysunku"],
      ["Wymiarowanie łańcuchowe na rysunku", "G91", "Odległości między elementami są podane wprost"],
      ["Powtarzalny wzór (rząd otworów, rowki)", "G91", "Jeden fragment kodu powtarzany w pętli"],
      ["Podprogram używany w wielu miejscach", "G91", "Działa niezależnie od punktu wywołania"],
      ["Odjazd do punktu referencyjnego", "G91", "`G91 G28 Z0` — „stąd prosto do góry”"],
      ["Program główny", "G90", "Odporny na przerwanie i wznowienie od dowolnego bloku"],
    ] },
    { t: "note", kind: "warn", x: "Program napisany w całości przyrostowo **nie da się bezpiecznie wznowić od środka**. Po zatrzymaniu narzędzia w połowie obróbki nie ma jak wrócić do właściwego punktu odniesienia — każdy kolejny ruch liczony jest od miejsca, w którym maszyna aktualnie stoi. To główny powód, dla którego G90 jest standardem w programie głównym." },
    { t: "sim", src: "G21 G90 G17 G54\nS2000 M03\nG00 X10 Y10 Z5\nG01 Z-2 F120\nG91\nG01 X30 F350\nG01 Y20\nG01 X-30\nG01 Y-20\nG90\nG00 Z5\nG00 X60 Y10\nG01 Z-2 F120\nG91\nG01 X30 F350\nG01 Y20\nG01 X-30\nG01 Y-20\nG90\nG00 Z5\nM30", caption: "Ten sam prostokąt wykonany dwa razy: zmienia się tylko punkt startowy, a fragment przyrostowy pozostaje identyczny. Właśnie ta cecha czyni G91 użytecznym w podprogramach." },
    { t: "h", x: "Tokarki Fanuc: U, W zamiast G91" },
    { t: "p", x: "Na tokarkach Fanuc zamiast przełączania trybu stosuje się **osobne adresy przyrostowe**: `U` dla osi X i `W` dla osi Z. Można je mieszać z absolutnymi w jednym bloku — `G01 X40 W-10` oznacza „jedź na średnicę 40 i przesuń się o 10 mm w lewo”. Uwaga: `U` jest **średnicowe**, tak jak `X`." },
    { t: "h", x: "Sinumerik: mieszanie w jednym bloku" },
    { t: "p", x: "Sinumerik pozwala określić tryb osobno dla każdej osi funkcjami `AC()` (bezwzględnie) i `IC()` (przyrostowo): `G1 X=AC(50) Y=IC(10)` oznacza „jedź do X równego 50 i przesuń się o 10 w Y”. To wygodne przy jednorazowych wyjątkach od trybu ustawionego globalnie." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak powrotu do G90** po fragmencie przyrostowym — dalsze bloki jadą w zupełnie inne miejsca.",
      "**`G90 G28 Z0`** — maszyna jedzie najpierw do Z0 detalu, czyli w materiał. Prawidłowo: `G91 G28 Z0`.",
      "**Podprogram przyrostowy, który nie wraca do punktu startu** — przy każdym powtórzeniu wzór przesuwa się o nadmiar.",
      "**Domyślne założenie trybu** — nie każdy sterownik startuje w G90. Blok bezpiecznego startu powinien go zawierać jawnie.",
    ] },
  ],

  "g81-g83": [
    { t: "p", x: "**Cykle stałe** zastępują kilkanaście bloków jednym. Zamiast pisać dojazd, zagłębienie, wycofanie i przejazd dla każdego otworu z osobna, definiujesz cykl raz, a potem podajesz same współrzędne kolejnych otworów. Sterownik powtarza w nich całą sekwencję." },
    { t: "h", x: "Anatomia cyklu wiercenia" },
    { t: "ol", items: [
      "Szybki przejazd do punktu X, Y.",
      "Szybki zjazd do **płaszczyzny R** — poziomu, od którego zaczyna się posuw roboczy, typowo 2–5 mm nad materiałem.",
      "Wiercenie z posuwem F do współrzędnej **Z** (dno otworu).",
      "Ewentualny postój na dnie albo wycofania z odprowadzeniem wióra.",
      "Powrót do płaszczyzny R (**G99**) albo do punktu początkowego (**G98**).",
    ] },
    { t: "diagram", id: "g81-g83" },
    { t: "h", x: "Najważniejsze cykle" },
    { t: "table", head: ["Kod", "Cykl", "Kiedy stosować"], rows: [
      ["**G81**", "Wiercenie proste — w dół i z powrotem", "Otwory płytkie, do 3× średnicy"],
      ["**G82**", "Wiercenie z postojem na dnie (adres P)", "Nawiercanie, pogłębianie czołowe — postój wygładza dno"],
      ["**G83**", "Wiercenie głębokie z **pełnym wycofaniem** co Q", "Otwory powyżej 3× średnicy, materiały z długim wiórem"],
      ["**G73**", "Wiercenie głębokie z **krótkim wycofaniem**", "Szybsze niż G83, ale gorzej usuwa wiór"],
      ["**G84**", "Gwintowanie gwintownikiem", "Posuw sprzężony z obrotami"],
      ["**G85**", "Wytaczanie z wyjściem na posuwie", "Otwory dokładne — brak śladu przy wyjściu"],
      ["**G80**", "Anulowanie cyklu", "Obowiązkowe po ostatnim otworze"],
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G99 G81 X20 Y20 Z-15 R2 F120     (pierwszy otwór — cykl zdefiniowany i wykonany)\nX50                              (drugi otwór, te same parametry)\nX50 Y50                          (trzeci)\nX20 Y50                          (czwarty)\nG80                              (koniec cyklu)\nG00 Z50", caption: "Cztery otwory w pięciu blokach. Bez cyklu wymagałoby to około dwudziestu." },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["X, Y", "Położenie otworu"],
      ["Z", "Współrzędna dna otworu (wartość ujemna względem zera detalu)"],
      ["R", "Płaszczyzna początku posuwu roboczego"],
      ["Q", "Głębokość jednego zagłębienia w G83 i G73"],
      ["P", "Czas postoju na dnie w milisekundach (G82, G89)"],
      ["F", "Posuw wiercenia"],
      ["K lub L", "Liczba powtórzeń — używane głównie z G91"],
    ] },
    { t: "h", x: "G98 kontra G99" },
    { t: "p", x: "Te dwie funkcje decydują, dokąd narzędzie wraca po każdym otworze. **G99** wraca tylko do płaszczyzny R — to szybsze, więc stosuje się je domyślnie. **G98** wraca do wysokości, na której narzędzie było przed rozpoczęciem cyklu — potrzebne, gdy między otworami znajduje się przeszkoda: zacisk, żebro odlewu, wcześniej obrobiony stopień." },
    { t: "note", kind: "tip", x: "Częsta praktyka: pracuj w G99, a przed otworem za przeszkodą wstaw pojedynczy blok z G98. Tryb jest modalny, więc pamiętaj o powrocie do G99 dla kolejnych otworów." },
    { t: "h", x: "Wiercenie głębokie" },
    { t: "p", x: "Powyżej trzech średnic wiór przestaje samodzielnie wychodzić z otworu — zaczyna się zakleszczać, rosną opory i temperatura. **G83** wycofuje wiertło **całkowicie do płaszczyzny R** po każdym zagłębieniu o Q, dzięki czemu wiór jest łamany i usuwany, a chłodziwo dociera do dna. Kosztem jest czas. **G73** wycofuje tylko o niewielką wartość (parametr maszynowy, zwykle 0,5–1 mm) — szybciej, ale wiór zostaje w otworze." },
    { t: "sim", src: "G21 G90 G17 G54\nS1200 M03\nG00 X20 Y20 Z10\nM08\nG01 Z-6 F100\nG00 Z2\nG01 Z-12 F100\nG00 Z2\nG01 Z-18 F100\nG00 Z10\nG00 X50 Y20\nG01 Z-6 F100\nG00 Z2\nG01 Z-12 F100\nG00 Z2\nG01 Z-18 F100\nG00 Z10\nM09\nM30", caption: "Ręcznie rozpisany odpowiednik cyklu G83 z Q6 dla dwóch otworów — dokładnie to, co sterownik robi wewnętrznie. Symulator nie interpretuje jeszcze cykli stałych, więc przykłady rozpisujemy jawnie." },
    { t: "h", x: "Sinumerik: cykle parametryczne" },
    { t: "p", x: "Sinumerik nie używa G81–G89, tylko wywołań z listą parametrów: `CYCLE81`, `CYCLE82`, `CYCLE83`, `CYCLE84` (gwintowanie), `CYCLE85`. Powtarzanie w kolejnych punktach realizuje modalne wywołanie `MCALL`:" },
    { t: "code", x: "MCALL CYCLE81(10, 0, 2, -15)   ; RTP, RFP, SDIS, DP\nX20 Y20\nX50 Y20\nX50 Y50\nMCALL                          ; wyłączenie wywołania modalnego", caption: "Odpowiednik cyklu G81 z czterema otworami w składni Sinumerik." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak G80 na końcu.** Kolejny blok ze współrzędnymi X Y — na przykład dojazd do frezowania — wykona jeszcze jeden otwór.",
      "**Płaszczyzna R poniżej powierzchni materiału.** Szybki zjazd do R oznacza wtedy wjazd wiertła w detal z prędkością szybką.",
      "**G99 przy zaciskach między otworami.** Klasyczna kolizja: narzędzie wraca tylko 2 mm nad materiał i uderza w zacisk.",
      "**Q większe od pozostałej głębokości** w ostatnim zagłębieniu — na części sterowników powoduje przekroczenie zadanego Z.",
      "**Cykl w trybie G91 bez przemyślenia** — Z i R liczone są wtedy przyrostowo, co daje zupełnie inne głębokości.",
    ] },
  ],
};
