import type { Block } from "@/lib/article";

const A = (blocks: Block[]) => blocks;

export const part1: Record<string, Block[]> = {
  g00: A([
    { t: "p", x: "**G00** nakazuje maszynie przemieścić narzędzie z aktualnej pozycji do zadanego punktu z **maksymalną prędkością posuwową**, jaką dopuszczają napędy. To ruch pozycjonujący, nie skrawający: służy do dojazdów nad detal, odjazdów na bezpieczną wysokość i przejazdów między obszarami obróbki." },
    { t: "h", x: "Co dokładnie robi G00" },
    { t: "p", x: "Sterownik odczytuje współrzędne docelowe i uruchamia wszystkie osie jednocześnie, każdą z jej własną maksymalną prędkością. Osie o krótszej drodze kończą ruch wcześniej, więc **tor wypadkowy nie jest linią prostą** — najczęściej wygląda jak odcinek pod kątem 45°, a potem prosty dobieg wzdłuż jednej osi. To zachowanie nazywa się pozycjonowaniem niezależnym osi (ang. *non-linear rapid*)." },
    { t: "note", kind: "warn", x: "Dokładnie ta właściwość jest przyczyną większości kolizji przy G00. Jeżeli między punktem A a B stoi zacisk albo wystaje ścianka detalu, „prosta droga” z Twojej wyobraźni nie odpowiada temu, którędy pojedzie maszyna." },
    { t: "p", x: "Część sterowników (Fanuc, Haas, Sinumerik) potrafi wymusić tor prostoliniowy przy szybkim przejeździe. W Fanuc odpowiada za to parametr maszynowy (LRP), w Sinumerik polecenia `RTLION` (ruch po prostej) i `RTLIOF` (niezależnie osiami). Nie zakładaj z góry, jak skonfigurowana jest Twoja maszyna — sprawdź to jednym ruchem próbnym z podniesionym narzędziem." },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G00 X_ Y_ Z_\nG0 X_ Y_ Z_        (zera wiodące są opcjonalne)", caption: "Zapis Fanuc i Sinumerik jest tu identyczny." },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [["X, Y, Z", "Współrzędne punktu docelowego — bezwzględne przy G90, przyrostowe przy G91"], ["A, B, C", "Osie obrotowe, jeśli maszyna je ma"], ["F", "Ignorowany. G00 zawsze jedzie z prędkością maksymalną, niezależnie od zaprogramowanego posuwu"]] },
    { t: "note", kind: "info", x: "G00 jest funkcją **modalną** z grupy ruchu (G00, G01, G02, G03). Raz włączona pozostaje aktywna aż do wywołania innej funkcji z tej samej grupy. Blok zawierający wyłącznie `G00`, bez współrzędnych, nie wykonuje żadnego ruchu — jedynie przełącza tryb." },
    { t: "h", x: "Prędkość szybkiego przejazdu" },
    { t: "p", x: "Prędkość G00 to parametr maszyny, nie programu. Typowe wartości: małe frezarki 5–15 m/min, centra obróbkowe 24–48 m/min, maszyny z napędem liniowym powyżej 60 m/min. Pokrętło **Rapid Override** na pulpicie (zwykle 5% / 25% / 50% / 100%) obniża tę prędkość — to podstawowe narzędzie przy pierwszym uruchomieniu nowego programu." },
    { t: "note", kind: "tip", x: "Przy pierwszym przebiegu ustaw Rapid Override na 5–25%, a korekcję posuwu na 50%, i trzymaj rękę nad przyciskiem zatrzymania posuwu. Uruchamianie nowego programu na 100% to najdroższy sposób sprawdzania, czy nie pomyliłeś się w zerze detalu." },
    { t: "h", x: "Prawidłowa kolejność dojazdu" },
    { t: "ol", items: [
      "G00 na bezpiecznej wysokości Z nad punktem startu obróbki — narzędzie porusza się wysoko nad wszystkim, co stoi na stole.",
      "G00 w płaszczyźnie XY do pozycji nad materiałem.",
      "G00 w dół do płaszczyzny bezpiecznej, typowo 2–5 mm nad powierzchnią materiału.",
      "G01 z posuwem roboczym na głębokość skrawania.",
    ] },
    { t: "p", x: "Ta kolejność — najpierw wysoko, potem nad miejscem, dopiero na końcu w dół — chroni przed najczęstszym błędem, czyli szybkim przejazdem przez materiał na poziomie obróbki." },
    { t: "sim", src: "G21 G90 G17 G54\nS1800 M03\nG00 Z50\nG00 X40 Y25\nG00 Z2\nG01 Z-3 F80\nG01 X90 F400\nG01 Y55\nG00 Z50\nM30", caption: "Prawidłowy schemat dojazdu. Żółta linia przerywana to G00, zielona ciągła — G01. Zwróć uwagę, że zejście na głębokość odbywa się dopiero po ustawieniu narzędzia nad właściwym miejscem." },
    { t: "h", x: "G00 kontra G01 — kiedy który" },
    { t: "table", head: ["Sytuacja", "Właściwy kod", "Dlaczego"], rows: [
      ["Dojazd nad materiał w powietrzu", "G00", "Skrócenie czasu jałowego"],
      ["Zejście na głębokość skrawania", "G01", "Kontrolowany posuw, brak uderzenia"],
      ["Przejazd między kieszeniami z narzędziem w materiale", "G01", "Narzędzie skrawa — G00 je złamie"],
      ["Odjazd na wysokość bezpieczną po obróbce", "G00", "Narzędzie już nie skrawa"],
      ["Wyjście z otworu po wierceniu", "G00 lub G01", "G01 przy wytaczaniu dokładnym, G00 przy zwykłym wierceniu"],
    ] },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Zejście G00 na ujemne Z nad materiałem.** Wystarczy jedno `G00 Z-5` zamiast `G01 Z-5` i narzędzie wbija się w detal z pełną prędkością.",
      "**Założenie prostoliniowego toru.** Przejazd „obok” zacisku po przekątnej często kończy się jego zaczepieniem.",
      "**Pozostawienie aktywnego G00 przed konturem.** Skoro G00 jest modalne, blok `X50 Y30` po wcześniejszym G00 też będzie szybkim przejazdem — nawet jeśli w Twojej głowie miał być ruchem roboczym.",
      "**Dojazd bez uwzględnienia długości narzędzia.** Bez aktywnego G43 sterownik liczy Z od czoła wrzeciona, nie od ostrza.",
    ] },
    { t: "note", kind: "tip", x: "Dobrym nawykiem jest odjazd na wysokość bezpieczną blokiem `G00 Z50` (albo `G91 G28 Z0`) przed każdą wymianą narzędzia i na końcu programu. Kosztuje ułamek sekundy, a zapobiega kolizji przy obrocie magazynu." },
  ]),

  g01: A([
    { t: "p", x: "**G01** prowadzi narzędzie po **linii prostej** z aktualnej pozycji do punktu docelowego, z prędkością zadaną adresem **F**. To podstawowy ruch skrawający — większość operacji frezowania konturów, planowania, toczenia wzdłużnego i poprzecznego opiera się właśnie na nim." },
    { t: "h", x: "Czym różni się od G00" },
    { t: "p", x: "Przy G01 sterownik oblicza prędkość każdej osi tak, aby **wszystkie zakończyły ruch w tym samym momencie**, a prędkość wypadkowa końcówki narzędzia była równa F. Dzięki temu tor jest zawsze idealną prostą, niezależnie od tego, ile osi bierze udział w ruchu. To nazywa się interpolacją liniową." },
    { t: "table", head: ["", "G00", "G01"], rows: [
      ["Tor", "Zwykle łamany, zależny od maszyny", "Zawsze linia prosta"],
      ["Prędkość", "Maksymalna maszyny", "Zaprogramowana adresem F"],
      ["Zastosowanie", "Dojazdy i odjazdy", "Skrawanie"],
      ["Adres F", "Ignorowany", "Wymagany"],
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G01 X_ Y_ Z_ F_\nG1 X_ Y_ Z_ F_" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["X, Y, Z", "Punkt końcowy ruchu (G90 — bezwzględnie, G91 — przyrostowo)"],
      ["F", "Posuw. Przy G94 w mm/min, przy G95 w mm na obrót wrzeciona"],
      ["A, B, C", "Osie obrotowe, jeśli występują"],
    ] },
    { t: "note", kind: "warn", x: "G01 bez wcześniej ustawionego F powoduje alarm na większości sterowników, a na niektórych — ruch z posuwem odziedziczonym z poprzedniej operacji, który może być wielokrotnie za duży. Posuw również jest modalny, więc raz podany obowiązuje aż do zmiany." },
    { t: "h", x: "Posuw: mm/min czy mm/obrót" },
    { t: "p", x: "Na frezarce standardem jest **G94**, czyli posuw minutowy w mm/min. Wartość liczy się ze wzoru: posuw = obroty × liczba ostrzy × posuw na ostrze. Frez ⌀10 z czterema ostrzami przy 3000 obr/min i fz = 0,05 mm daje F = 3000 × 4 × 0,05 = **600 mm/min**." },
    { t: "p", x: "Na tokarce standardem jest **G95**, czyli posuw na obrót w mm/obr. Ta jednostka jest wygodniejsza, bo bezpośrednio wpływa na chropowatość powierzchni i grubość wióra, niezależnie od aktualnych obrotów. Typowe wartości: zgrubnie 0,25–0,45 mm/obr, wykańczająco 0,08–0,20 mm/obr." },
    { t: "note", kind: "warn", x: "Pomylenie jednostek jest jednym z najkosztowniejszych błędów w programowaniu. `F0.2` na frezarce w trybie G94 oznacza 0,2 mm/min — narzędzie praktycznie stoi i wypala się w materiale. Odwrotnie, `F200` na tokarce w trybie G95 to 200 mm na obrót, czyli natychmiastowe złamanie płytki." },
    { t: "h", x: "Zagłębianie w materiał" },
    { t: "p", x: "Ruch w osi Z prosto w dół obciąża narzędzie zupełnie inaczej niż ruch boczny — pracuje wtedy środek freza, gdzie prędkość skrawania spada do zera. Dlatego posuw zagłębiania przyjmuje się na poziomie **30–50% posuwu konturowego**. Frezy o środku niecentrującym (większość frezów wieloostrzowych do stali) w ogóle nie mogą zagłębiać się pionowo." },
    { t: "ul", items: [
      "**Zagłębianie pionowe (G01 Z−)** — tylko frezami do zagłębiania pionowego lub w otwór wstępny.",
      "**Zagłębianie po rampie** — ruch skośny G01 z jednoczesną zmianą X i Z, kąt 2–5° dla stali, do 15° dla aluminium.",
      "**Zagłębianie po helisie** — łuk G02/G03 z narastającym Z; najłagodniejsze dla narzędzia, opisane na karcie G02/G03.",
    ] },
    { t: "sim", src: "G21 G90 G17 G54\nS2400 M03\nG00 X0 Y0 Z5\nG01 Z-2 F150\nG01 X60 F450\nG01 X70 Y10\nG01 Y40\nG01 X10\nG01 X0 Y30\nG01 Y0\nG00 Z5\nM30", caption: "Kontur zamknięty z dwoma odcinkami skośnymi. Podczas ruchu skośnego obie osie pracują jednocześnie, ale prędkość wypadkowa pozostaje równa F." },
    { t: "h", x: "Zagłębianie po rampie — przykład" },
    { t: "sim", src: "G21 G90 G17 G54\nS3000 M03\nG00 X10 Y20 Z2\nG01 X50 Z-1 F250\nG01 X10 Z-2\nG01 X50 Z-3\nG01 X10 Z-4\nG01 X50 F400\nG01 Y30\nG01 X10\nG00 Z5\nM30", caption: "Narzędzie schodzi po 1 mm na każdym przejściu wzdłuż rowka, zamiast wbijać się pionowo. Włącz widok 3D, żeby zobaczyć powstający rowek." },
    { t: "h", x: "Modalność w praktyce" },
    { t: "p", x: "Ponieważ G01 pozostaje aktywne, kontur można zapisać bardzo zwięźle — wystarczą same współrzędne. Poniższe dwa zapisy są równoważne:" },
    { t: "code", x: "G01 X60 F400        G01 X60 F400\nG01 Y40 F400        Y40\nG01 X0 F400         X0\nG01 Y0 F400         Y0", caption: "Zapis pełny (po lewej) i skrócony (po prawej). W praktyce stosuje się ten drugi — jest krótszy i mniej podatny na literówki." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak F w pierwszym bloku roboczym** — alarm albo posuw z poprzedniej operacji.",
      "**Ten sam posuw do zagłębiania i do konturu** — przeciążenie środka freza.",
      "**Pozostawienie G01 przed odjazdem** — powrót na wysokość bezpieczną z posuwem roboczym marnuje czas cyklu; użyj G00.",
      "**Kontur niedomknięty** — ostatni punkt nie pokrywa się z pierwszym, zostaje cienka ścianka materiału.",
    ] },
  ]),
};
