import type { Block } from "@/lib/article";

export const part4: Record<string, Block[]> = {

  g28: [
    { t: "p", x: "**G28** odsyła podane osie do **punktu referencyjnego maszyny** — położenia wyznaczonego przy bazowaniu i zapisanego przez producenta w parametrach. Ruch odbywa się dwuetapowo, ruchem szybkim: najpierw do punktu pośredniego podanego w bloku, potem do punktu referencyjnego." },
    { t: "h", x: "Punkt pośredni w G90 i w G91" },
    { t: "p", x: "Współrzędne w bloku G28 opisują **punkt pośredni**, a ich znaczenie zależy od aktywnego trybu wymiarowania:" },
    { t: "ul", items: [
      "**G91 G28 Z0** — przyrost 0 od bieżącej pozycji: pierwszy etap nie wykonuje ruchu, zostaje sam przejazd do punktu referencyjnego Z.",
      "**G90 G28 Z0** — punkt pośredni to Z0 układu detalu. Jeżeli Z0 leży na powierzchni detalu, a narzędzie stoi tuż nad nią, pierwszy etap schodzi ruchem szybkim na detal.",
      "**G90 G28 Z50** — punkt pośredni 50 mm nad zerem detalu: bezpieczny tylko wtedy, gdy na tej wysokości nie ma przeszkód.",
    ] },
    { t: "diagram", id: "g28-path" },
    { t: "code", x: "; założenia: frezarka pionowa, Fanuc, G21, G54 z Z0 na górze detalu\nG91 G28 Z0     ; punkt pośredni = bieżąca pozycja, potem punkt referencyjny Z\nG90            ; powrót do trybu absolutnego", caption: "Fragment ilustrujący — nie kompletny program." },
    { t: "note", kind: "warn", x: "Drugi etap prowadzi tam, gdzie producent ustawił punkt referencyjny. Na typowej frezarce pionowej to górne położenie osi Z, ale nie jest to reguła dla każdej maszyny — przed użyciem G28 sprawdź jego położenie w dokumentacji maszyny i to, czy droga do niego jest wolna (zaciski, wysokie elementy, oś obrotowa)." },
    { t: "h", x: "Kiedy się stosuje" },
    { t: "ul", items: [
      "Przed wymianą narzędzia — magazyn wymaga określonej pozycji Z.",
      "Na końcu programu — odsunięcie narzędzia i udostępnienie stołu.",
      "Przed obrotem stołu lub głowicy na maszynach wieloosiowych.",
    ] },
    { t: "h", x: "Kody pokrewne" },
    { t: "table", head: ["Kod", "Działanie"], rows: [
      ["**G27**", "Sprawdzenie, czy oś rzeczywiście dojechała do punktu referencyjnego"],
      ["**G28**", "Powrót do pierwszego punktu referencyjnego"],
      ["**G29**", "Powrót z punktu referencyjnego przez ten sam punkt pośredni"],
      ["**G30**", "Powrót do drugiego, trzeciego lub czwartego punktu referencyjnego (P2–P4)"],
    ] },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "W **trybie ISO** (dialekt Fanuc, włączany np. przez `G291`) Sinumerik obsługuje G28 z punktem pośrednim. W **języku natywnym** Siemensa te same zadania realizują inne funkcje: **G74** — najazd na punkt referencyjny, **G75** — na punkt stały z danych maszynowych. `SUPA` jedynie wyłącza przesunięcia w danym bloku (ruch we współrzędnych maszynowych) — nie jest zamiennikiem powrotu do punktu referencyjnego." },
    { t: "note", kind: "info", x: "Źródło: Siemens, SINUMERIK 840D sl / 828D ISO Milling, instrukcja programowania 02/2012 (6FC5398-7BP40-3BA0), rozdz. 2.2.1 „Reference point approach with intermediate point (G28)”. Szczegóły G74/G75 w języku natywnym — do weryfikacji w instrukcji programowania dla wersji sterowania." },
  ],

  "g52-g53": [
    { t: "p", x: "**G52** ustawia **układ lokalny** — dodatkowe przesunięcie nakładane na aktywny G54–G59. **G53** działa odwrotnie: na jeden blok wyłącza wszystkie przesunięcia i każe interpretować współrzędne jako **maszynowe**." },
    { t: "h", x: "G52 — układ lokalny" },
    { t: "p", x: "Przydaje się, gdy detal ma kilka identycznych elementów rozmieszczonych w znanych odległościach. Zamiast przeliczać współrzędne każdego, przesuwasz zero i wywołujesz ten sam fragment programu." },
    { t: "code", x: "G54\nG52 X0 Y0        ; pierwszy element — bez przesunięcia\nM98 P1001\nG52 X60 Y0       ; drugi element, 60 mm dalej w X\nM98 P1001\nG52 X60 Y40      ; trzeci\nM98 P1001\nG52 X0 Y0        ; skasowanie układu lokalnego" },
    { t: "note", kind: "warn", x: "G52 **nie kasuje się samo** po zakończeniu programu na części sterowników. Zapomniane `G52 X60` zostaje aktywne i przesuwa obróbkę następnego detalu. Zawsze kończ blokiem `G52 X0 Y0 Z0`." },
    { t: "h", x: "G53 — współrzędne maszynowe" },
    { t: "p", x: "G53 obowiązuje **wyłącznie w bloku, w którym stoi**. Współrzędne odnoszą się do zera maszyny, więc pozycja jest niezależna od tego, jak ustawione są rejestry detalu. Stosuje się to do:" },
    { t: "ul", items: [
      "dojazdu do pozycji wymiany narzędzia,",
      "odjazdu na pozycję załadunku i wyładunku detalu,",
      "przejazdu ponad przeszkodami o znanym położeniu na stole.",
    ] },
    { t: "code", x: "G53 G00 Z0          ; oś Z do samej góry, niezależnie od G54\nG53 G00 X-500 Y0    ; stół wysunięty do operatora", caption: "G53 wymaga trybu G90 i działa tylko z G00 lub G01." },
    { t: "h", x: "Sinumerik" },
    { t: "table", head: ["Funkcja", "Fanuc", "Sinumerik"], rows: [
      ["Układ lokalny", "G52", "`TRANS` (bezwzględnie), `ATRANS` (przyrostowo)"],
      ["Współrzędne maszynowe", "G53", "`SUPA` (dawniej `G153`)"],
      ["Skalowanie", "G50/G51", "`SCALE`, `ASCALE`"],
      ["Odbicie lustrzane", "G50.1/G51.1", "`MIRROR`, `AMIRROR`"],
    ] },
  ],

  "g68-g69": [
    { t: "p", x: "**G68** obraca układ współrzędnych o zadany kąt wokół wskazanego punktu. Wszystkie kolejne współrzędne są interpretowane w układzie obróconym, aż do **G69**." },
    { t: "h", x: "Do czego to służy" },
    { t: "ul", items: [
      "**Detale zamocowane pod kątem** — zamiast przeliczać cały kontur, obracasz układ o kąt zamocowania.",
      "**Elementy powtarzane po okręgu** — sześć kieszeni co 60° to jeden podprogram wywołany sześć razy z różnym kątem.",
      "**Rysunki wymiarowane pod kątem** — przepisujesz wymiary wprost, bez trygonometrii.",
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G68 X0 Y0 R30      ; obrót o 30° wokół punktu (0,0)\nM98 P1002          ; obrabiany element\nG69                ; kasowanie obrotu" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["X, Y", "Środek obrotu, w aktywnej płaszczyźnie"],
      ["R", "Kąt w stopniach; wartość dodatnia oznacza obrót przeciwnie do wskazówek zegara"],
    ] },
    { t: "code", x: "G54\nG68 X0 Y0 R0\nM98 P1002\nG69\nG68 X0 Y0 R60\nM98 P1002\nG69\nG68 X0 Y0 R120\nM98 P1002\nG69", caption: "Trzy identyczne elementy rozmieszczone co 60° wokół środka detalu." },
    { t: "note", kind: "warn", x: "Zapomniane **G69** zostaje aktywne dla kolejnych narzędzi — cała reszta programu wykona się w obróconym układzie. Dlatego G69 warto umieścić także w bloku bezpiecznego startu po każdej wymianie narzędzia." },
    { t: "note", kind: "info", x: "Symulator nie interpretuje jeszcze G68 — pokazuje kontur bazowy, bez obrotu. Na maszynie obrót zadziała normalnie." },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "Odpowiedniki to **`ROT RPL=30`** (obrót bezwzględny w płaszczyźnie) i **`AROT RPL=30`** (obrót dodawany do już aktywnego). Samo `ROT` bez parametrów kasuje obrót, tak jak G69." },
  ],

  g92: [
    { t: "p", x: "**G92** przypisuje aktualnemu położeniu narzędzia zadane współrzędne. Maszyna się nie porusza — zmienia się tylko sposób liczenia. To metoda ustawiania zera sprzed epoki rejestrów G54, dziś spotykana głównie w starszych programach i na prostych sterownikach." },
    { t: "h", x: "Jak to działa" },
    { t: "p", x: "Ustawiasz narzędzie w narożniku detalu i piszesz `G92 X0 Y0 Z0`. Od tej chwili sterownik uznaje to miejsce za zero. Efekt jest podobny do G54, ale z istotną różnicą: **przesunięcie jest liczone od miejsca, w którym maszyna aktualnie stoi**, a nie zapisane na stałe w rejestrze." },
    { t: "note", kind: "warn", x: "Stąd bierze się główne niebezpieczeństwo. Jeżeli program z G92 zostanie uruchomiony, gdy narzędzie stoi gdzie indziej niż za pierwszym razem, **cała obróbka przesunie się o tę różnicę**. Program z G54 jest w tej sytuacji odporny, bo rejestr pamięta położenie bezwzględne." },
    { t: "h", x: "G92 na tokarce" },
    { t: "p", x: "Na tokarkach Fanuc starszych serii `G92 S2500` pełni zupełnie inną funkcję: **ogranicza maksymalne obroty** przy stałej prędkości skrawania G96. W nowszych sterownikach ten sam limit zapisuje się jako `G50 S2500`. Ten sam kod, dwa różne znaczenia zależnie od typu maszyny — kolejna pułapka przy przenoszeniu programów." },
    { t: "h", x: "Kiedy jeszcze się przydaje" },
    { t: "ul", items: [
      "Maszyny bez rejestrów układów współrzędnych (proste sterowniki, obrabiarki hobbystyczne, GRBL).",
      "Tymczasowe przesunięcie zera wewnątrz programu przy pracy z podprogramami.",
      "Programy generowane przez starsze postprocesory.",
    ] },
    { t: "note", kind: "tip", x: "Jeżeli maszyna ma G54–G59, używaj ich. Są bezpieczniejsze, czytelniejsze i nie giną po restarcie sterownika." },
  ],

  "m98-m99": [
    { t: "p", x: "**M98** wywołuje podprogram, **M99** kończy go i zwraca sterowanie do miejsca wywołania. Podprogramy pozwalają zapisać powtarzalny fragment raz i wywołać go wielokrotnie — z różnymi układami współrzędnych, kątami czy przesunięciami." },
    { t: "h", x: "Struktura" },
    { t: "code", x: "O0100 (PROGRAM GLOWNY)\nG21 G90 G17 G54 G40 G49 G80\nT01 M06\nG43 H01 Z50\nS2000 M03\nM98 P1001          ; wywołanie podprogramu O1001\nG55\nM98 P1001          ; ten sam kształt w drugim zamocowaniu\nG91 G28 Z0\nG90\nM30\n\nO1001 (PODPROGRAM — KIESZEN)\nG00 X10 Y10\nG00 Z2\nG01 Z-3 F120\nG01 X50 F400\nG01 Y30\nG01 X10\nG01 Y10\nG00 Z50\nM99                ; powrót do programu głównego" },
    { t: "h", x: "Powtórzenia" },
    { t: "table", head: ["Zapis", "Znaczenie"], rows: [
      ["`M98 P1001`", "Jedno wywołanie podprogramu numer 1001"],
      ["`M98 P51001`", "**Pięć** wywołań podprogramu 1001 — liczba powtórzeń stoi z przodu"],
      ["`M98 P1001 L5`", "To samo, składnia z osobnym adresem L (nie wszystkie sterowniki)"],
    ] },
    { t: "note", kind: "warn", x: "Zapis `P51001` bywa mylący, bo wygląda jak numer programu 51001. Sterownik czyta ostatnie cztery cyfry jako numer, a to, co przed nimi, jako liczbę powtórzeń." },
    { t: "h", x: "Podprogramy przyrostowe" },
    { t: "p", x: "Największą siłę podprogramy pokazują w połączeniu z G91. Podprogram wykonujący jeden element, zakończony powrotem do punktu startu i przesunięciem o krok, powtórzony pięć razy daje rząd pięciu identycznych elementów — bez liczenia współrzędnych." },
    { t: "code", x: "O0200\nG21 G90 G17 G54\nS2200 M03\nG00 X10 Y10 Z5\nG91\nM98 P51002        ; pięć rowków co 15 mm\nG90\nG00 Z50\nM30\n\nO1002\nG01 Z-7 F120\nG01 X20 F400\nG00 Z7\nG00 X-20 Y15     ; powrót i przesunięcie o krok\nM99", caption: "Podprogram kończy się dokładnie o jeden krok dalej niż zaczął — to warunek poprawnego powtarzania." },
    { t: "note", kind: "warn", x: "**M99 w programie głównym tworzy pętlę nieskończoną.** Program wraca na początek i wykonuje się od nowa, aż do zatrzymania przez operatora. To bywa używane celowo (praca ciągła z podajnikiem), ale przypadkowo jest bardzo nieprzyjemne." },
    { t: "h", x: "Sinumerik" },
    { t: "table", head: ["Funkcja", "Fanuc", "Sinumerik"], rows: [
      ["Wywołanie", "`M98 P1001`", "`L1001` albo nazwa: `KIESZEN`"],
      ["Powtórzenia", "`M98 P51001`", "`L1001 P5`"],
      ["Koniec podprogramu", "`M99`", "`M17` albo `RET`"],
      ["Przekazywanie parametrów", "makra G65 ze zmiennymi #", "parametry w definicji `PROC`"],
    ] },
  ],

  g84: [
    { t: "p", x: "**G84** wykonuje gwint gwintownikiem. Cykl wkręca narzędzie na zadaną głębokość, zatrzymuje wrzeciono, odwraca kierunek obrotów i wykręca gwintownik — wszystko w jednym bloku." },
    { t: "h", x: "Warunek podstawowy: posuw musi wynikać ze skoku" },
    { t: "p", x: "Gwintownik musi przesuwać się dokładnie o skok gwintu na każdy obrót. Jednostkę F wyznacza aktywny tryb posuwu, dlatego w niezależnym przykładzie trzeba go ustawić jawnie:" },
    { t: "table", head: ["Tryb (frezarka, mm)", "F", "M10×1,5 przy 400 obr/min"], rows: [
      ["**G94** — mm/min", "obroty × skok", "F600"],
      ["**G95** — mm/obr", "skok", "F1.5"],
    ], caption: "Na frezarce G98/G99 wybierają poziom powrotu w cyklu — nie jednostkę posuwu (to znaczenie mają na tokarkach Fanuc w systemie A)." },
    { t: "note", kind: "warn", x: "Błąd w tym obliczeniu prowadzi do złamania gwintownika w otworze — jednej z najbardziej uciążliwych awarii, bo hartowanego gwintownika nie da się wywiercić." },
    { t: "h", x: "Gwintowanie sztywne kontra z kompensacją" },
    { t: "ul", items: [
      "**Gwintowanie sztywne** — sterowanie synchronizuje obrót wrzeciona z posuwem osi Z, bez uchwytu kompensacyjnego. Na wielu sterowaniach Fanuc włącza je `M29 S_` przed cyklem; sposób włączenia zależy od parametrów maszyny i producenta.",
      "**Gwintowanie z uchwytem kompensacyjnym** — uchwyt ma sprężynę wyrównującą drobne różnice między posuwem a skokiem. Rozwiązanie starsze, wymaga specjalnego uchwytu i zapasu skoku w otworze.",
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "; założenia: frezarka, Fanuc z gwintowaniem sztywnym przez M29, G21, G17, G90, G54,\n; narzędzie nad otworem na wysokości bezpiecznej, M10x1,5, 400 obr/min\nG94                               ; posuw mm/min\nM29 S400\nG99 G84 X20 Y20 Z-18 R5 F600      ; F = 400 x 1,5\nX60\nG80\n\n; ten sam cykl w G95 (jeśli maszyna obsługuje posuw na obrót przy gwintowaniu)\nG95                               ; posuw mm/obr\nM29 S400\nG99 G84 X20 Y20 Z-18 R5 F1.5      ; F = skok\nG80\nG94", caption: "Fragment ilustrujący. Z−18 to położenie końca gwintownika, nie długość gwintu." },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["Z", "Położenie końca gwintownika na dnie cyklu [mm]"],
      ["R", "Płaszczyzna startu posuwu [mm]; zapas na rozbieg"],
      ["F", "G94: obroty × skok [mm/min]; G95: skok [mm/obr]"],
      ["P", "Postój na dnie przed zmianą kierunku [ms] — jeśli sterowanie go obsługuje"],
    ] },
    { t: "h", x: "Cztery różne głębokości" },
    { t: "p", x: "Pełny gwint, nakrój gwintownika, położenie końca narzędzia i głębokość otworu to cztery różne wartości. Nakrój (zbieżna część gwintownika) nie tnie pełnego zarysu, więc koniec narzędzia musi zejść głębiej niż żądany pełny gwint, a otwór — jeszcze głębiej." },
    { t: "diagram", id: "g84-depths" },
    { t: "code", x: "pełny gwint L = 15 mm, nakrój ≈ 3 zwoje × 1,5 = 4,5 mm (założenie dla danego gwintownika)\nZ końca gwintownika = −(15 + 4,5) = −19,5\notwór ≥ 19,5 + zapas (np. 2,5) = 22 mm, plus stożek wiertła", caption: "Długość nakroju zależy od formy gwintownika — wartość z katalogu narzędzia." },
    { t: "h", x: "Otwór wstępny" },
    { t: "p", x: "Dla **gwintowników skrawających** i gwintów metrycznych zwykłych średnicę otworu przyjmuje się w przybliżeniu jako **średnica nominalna minus skok**. Wygniataki (gwintowniki bezwiórowe) potrzebują większego otworu — jego średnica pochodzi z katalogu producenta narzędzia." },
    { t: "table", head: ["Gwint", "Skok [mm]", "Otwór [mm]"], rows: [
      ["M5", "0,8", "4,2"], ["M6", "1,0", "5,0"], ["M8", "1,25", "6,8"],
      ["M10", "1,5", "8,5"], ["M12", "1,75", "10,2"], ["M16", "2,0", "14,0"], ["M20", "2,5", "17,5"],
    ] },
    { t: "sim", src: "G21 G90 G17 G54 G80\nT01 M06\nS400 M03\nG00 X20 Y20\nG43 Z10 H01\nG99 G84 X20 Y20 Z-18 R5 F600\nX60\nY45\nX20\nG80\nG00 Z50\nM05\nM30", caption: "Cztery gwinty M10 cyklem G84. Symulator rozwija cykl na ruchy elementarne — wejście i wyjście odbywają się na posuwie roboczym." },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "**`CYCLE84`** — gwintowanie sztywne, **`CYCLE840`** — z uchwytem kompensacyjnym. Skok, kierunek gwintu i pozostałe dane podaje się parametrami cyklu; ich nazwy i kolejność zależą od wydania cykli, więc nie przenoś parametrów jednego cyklu do drugiego. Korzystaj z formularza cyklu na sterowaniu albo z dokumentacji „Cykle” dla swojej wersji." },
    { t: "note", kind: "info", x: "Źródło zależności F = skok × obroty (G94) i F = skok (G95): Haas Automation, „G84 Tapping Canned Cycle”, AP-602, 04/2016 — dokument dla frezarek Haas; na innych sterowaniach potwierdź w ich dokumentacji." },
  ],

  "g85-g86": [
    { t: "p", x: "Cykle wytaczania różnią się sposobem **wyjścia narzędzia z otworu** — i właśnie ta różnica decyduje o jakości powierzchni." },
    { t: "table", head: ["Kod", "Wyjście z otworu", "Efekt"], rows: [
      ["**G85**", "Na posuwie roboczym, wrzeciono pracuje", "Brak śladu; wytaczak przechodzi drugi raz, powierzchnia gładsza"],
      ["**G86**", "Stop wrzeciona, wyjście szybkie", "Szybko, ale ostrze może zostawić rysę wzdłuż ściany"],
      ["**G89**", "Postój na dnie, potem wyjście na posuwie", "Jak G85 plus wyrównanie dna"],
      ["**G76**", "Orientacja wrzeciona, odsunięcie ostrza, wyjście szybkie", "Najlepszy — ostrze nie dotyka ściany przy wyjściu"],
      ["**G87**", "Wytaczanie wsteczne, od dołu otworu", "Podtoczenia i powierzchnie niedostępne od góry"],
    ] },
    { t: "h", x: "Kiedy który" },
    { t: "ul", items: [
      "**Otwór na wymiar tolerowany (H7)** — G85 albo G76. Rysa od G86 potrafi zepsuć powierzchnię obrobioną na gotowo.",
      "**Otwór zgrubny, bez wymagań** — G86 jest po prostu szybszy.",
      "**Dno płaskie na wymiar** — G89 z postojem.",
      "**Wytaczak z płytką jednostronną** — G76, jeśli maszyna obsługuje orientację wrzeciona.",
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G99 G85 X30 Y30 Z-25 R2 F80      ; wytaczanie, wyjście na posuwie\nG80\nG99 G86 X70 Y30 Z-25 R2 F120     ; wytaczanie, wyjście szybkie\nG80" },
    { t: "sim", src: "G21 G90 G17 G54 G80\nT01 M06\nS900 M03\nG00 X30 Y30\nG43 Z10 H01\nM08\nG99 G85 X30 Y30 Z-25 R2 F80\nG80\nG00 Z50\nM09\nM30", caption: "Cykl G85 — zwróć uwagę, że wyjście z otworu jest ruchem roboczym (zielona linia), a nie szybkim przejazdem." },
    { t: "note", kind: "tip", x: "Przy wytaczaniu na wymiar warto zostawić 0,2–0,4 mm naddatku po wierceniu i pracować z posuwem 0,05–0,12 mm/obr. Wytaczak jest długi i podatny na drgania — mniejszy naddatek daje lepszą powierzchnię niż większy posuw." },
  ],

  g33: [
    { t: "p", x: "**G33** (na części sterowników Fanuc **G32**) wykonuje **jedno przejście gwintu**, prowadząc narzędzie ze skokiem zsynchronizowanym z obrotami wrzeciona. Podział na przejścia i dobór głębokości należą do programisty — w odróżnieniu od cyklu G76, który robi to sam." },
    { t: "h", x: "Na czym polega synchronizacja" },
    { t: "p", x: "Sterownik odczytuje sygnał z enkodera wrzeciona i startuje ruch osi zawsze **w tym samym położeniu kątowym**. Dzięki temu kolejne przejścia trafiają dokładnie w tę samą nitkę. Gdyby start nie był zsynchronizowany, każde przejście nacinałoby gwint w innym miejscu obwodu." },
    { t: "note", kind: "warn", x: "Z tego samego powodu gwintowanie musi odbywać się przy **G97** — stałych obrotach. Przy G96 obroty zmieniają się wraz ze średnicą, a wraz z nimi rzeczywisty skok." },
    { t: "h", x: "Rozbieg i wybieg" },
    { t: "p", x: "Osie potrzebują drogi na rozpędzenie się do prędkości odpowiadającej skokowi. Zasada: **rozbieg ≥ 2 × skok**, przy dużych skokach i obrotach nawet 4 × skok. Bez tego pierwsze zwoje mają zaniżony skok i są zniekształcone. Analogicznie na końcu potrzebny jest wybieg albo rowek podcięcia." },
    { t: "h", x: "Składnia" },
    { t: "code", x: "; Fanuc\nG00 X23.2 Z5\nG32 Z-25 F1.5\nG00 X30\nG00 Z5\n\n; Sinumerik\nG0 X23.2 Z5\nG33 Z-25 K1.5\nG0 X30\nG0 Z5", caption: "Jedno przejście. Pełny gwint wymaga powtórzenia tego bloku z coraz mniejszą średnicą X." },
    { t: "sim", mode: "lathe", src: "G18 G21 G40 G99\nG97 S700 M03\nG00 X26 Z6\nG00 X23.2\nG01 Z-25 F1.5\nG00 X30\nG00 Z6\nG00 X22.6\nG01 Z-25 F1.5\nG00 X30\nG00 Z6\nG00 X22.1\nG01 Z-25 F1.5\nG00 X30\nG00 Z6\nG00 X21.8\nG01 Z-25 F1.5\nG00 X30\nG00 Z6\nM30", caption: "Cztery przejścia gwintu M24×1,5 o malejącym przyroście głębokości: 0,4 / 0,3 / 0,25 / 0,15 mm." },
    { t: "h", x: "G33 kontra G76" },
    { t: "table", head: ["", "G33 / G32", "G76"], rows: [
      ["Podział na przejścia", "Ręczny", "Automatyczny"],
      ["Kontrola nad każdym przejściem", "Pełna", "Ograniczona parametrami"],
      ["Długość zapisu", "Kilka bloków na przejście", "Dwa bloki na cały gwint"],
      ["Zastosowanie", "Gwinty nietypowe, wielozwojne, naprawcze", "Standardowe gwinty produkcyjne"],
    ] },
  ],

  "m08-m09": [
    { t: "p", x: "**M08** włącza chłodziwo zalewowe, **M07** mgłę olejową, **M09** wyłącza oba. Funkcje modalne — raz włączone działają aż do wyłączenia albo do końca programu (M30 wyłącza chłodziwo automatycznie)." },
    { t: "h", x: "Rodzaje chłodzenia" },
    { t: "table", head: ["Kod", "Rodzaj", "Zastosowanie"], rows: [
      ["**M07**", "Mgła olejowa", "Aluminium, obróbka wykańczająca, maszyny bez wanny"],
      ["**M08**", "Zalewowe (emulsja)", "Standard: stal, żeliwo, obróbka zgrubna"],
      ["**M09**", "Wyłączenie", "Obie postacie naraz"],
      ["**M88 / M89**", "Chłodzenie przez narzędzie (na części maszyn)", "Wiercenie głębokie, otwory powyżej 5× średnicy"],
    ] },
    { t: "h", x: "Po co w ogóle chłodziwo" },
    { t: "ul", items: [
      "**Odprowadzenie ciepła** — najważniejsze przy materiałach o niskiej przewodności, takich jak stal nierdzewna i tytan.",
      "**Wypłukiwanie wióra** — kluczowe przy wierceniu i frezowaniu rowków, gdzie wiór nie ma jak wyjść.",
      "**Smarowanie** — zmniejsza tarcie i narost na ostrzu, poprawia powierzchnię.",
    ] },
    { t: "note", kind: "warn", x: "Przy obróbce **żeliwa** i przy frezowaniu **węglikiem na sucho** chłodziwo bywa szkodliwe. Węglik źle znosi szok termiczny: przerywany strumień chłodziwa na gorące ostrze powoduje mikropęknięcia i wykruszanie. Jeżeli chłodzisz węglik, chłodź obficie i bez przerw." },
    { t: "note", kind: "info", x: "**Tylko jedna funkcja M w bloku** na sterownikach Fanuc. Dlatego `S2000 M03` i `M08` to dwie osobne linie." },
  ],

  m30: [
    { t: "p", x: "**M30** kończy program, zatrzymuje wrzeciono i chłodziwo, kasuje funkcje modalne i przewija program na początek. **M02** kończy program bez przewijania." },
    { t: "h", x: "Co dokładnie robi M30" },
    { t: "ul", items: [
      "zatrzymuje wrzeciono (jak M05),",
      "wyłącza chłodziwo (jak M09),",
      "kasuje funkcje modalne do stanu domyślnego sterownika,",
      "ustawia kursor na pierwszym bloku, gotowy do kolejnej sztuki,",
      "zwiększa licznik wykonanych detali.",
    ] },
    { t: "h", x: "Zakończenie programu w praktyce" },
    { t: "p", x: "Samo M30 nie odsuwa narzędzia. Pełne, bezpieczne zakończenie wygląda tak:" },
    { t: "code", x: "G00 Z50          ; odjazd na wysokość bezpieczną\nM09              ; chłodziwo wyłączone\nM05              ; wrzeciono zatrzymane\nG91 G28 Z0       ; oś Z do bazy\nG90              ; powrót do trybu absolutnego\nM30              ; koniec programu", caption: "Kolejność ma znaczenie: najpierw wyjdź z materiału, potem wyłączaj." },
    { t: "table", head: ["Kod", "Działanie"], rows: [
      ["**M00**", "Zatrzymanie bezwarunkowe w środku programu — do pomiaru albo obrócenia detalu. Wznowienie przyciskiem Start"],
      ["**M01**", "Zatrzymanie warunkowe — działa tylko, gdy operator włączył Optional Stop na pulpicie"],
      ["**M02**", "Koniec programu bez przewijania"],
      ["**M30**", "Koniec programu z przewijaniem — standard"],
      ["**M99**", "Koniec podprogramu; w programie głównym powoduje pętlę nieskończoną"],
    ] },
    { t: "note", kind: "tip", x: "**M01** to bardzo przydatne narzędzie przy uruchamianiu nowego programu. Wstaw je po każdym narzędziu — przy włączonym Optional Stop maszyna zatrzyma się po każdym zabiegu, żebyś mógł zmierzyć detal. Po zatwierdzeniu programu wyłączasz Optional Stop i te same bloki są ignorowane." },
  ],
};
