import type { Block } from "@/lib/article";

export const part3: Record<string, Block[]> = {
  "g96-g97": [
    { t: "p", x: "**G96** i **G97** decydują, co oznacza liczba przy adresie **S**. Przy **G97** jest to bezpośrednio prędkość obrotowa wrzeciona w obr/min. Przy **G96** — **prędkość skrawania w m/min**, a obroty sterownik przelicza sam, na bieżąco, w zależności od aktualnej średnicy toczenia." },
    { t: "h", x: "Dlaczego to ma znaczenie" },
    { t: "p", x: "Prędkość skrawania — czyli prędkość, z jaką materiał przesuwa się względem ostrza — zależy od średnicy: **Vc = π · D · n / 1000**. Podczas toczenia poprzecznego (planowania czoła) średnica maleje od zewnątrz do osi. Przy stałych obrotach prędkość skrawania spada wtedy proporcjonalnie i w pobliżu osi dochodzi do zera: ostrze przestaje skrawać, zaczyna gnieść materiał, powierzchnia się psuje, a płytka wykrusza." },
    { t: "p", x: "**G96 utrzymuje Vc na stałym poziomie**, podnosząc obroty w miarę zmniejszania średnicy. Efekt: równa chropowatość na całej powierzchni czoła i przewidywalna trwałość ostrza." },
    { t: "diagram", id: "g96-g97" },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G50 S3000          (Fanuc: ograniczenie obrotów — obowiązkowe przed G96)\nG96 S220 M03       (stała prędkość skrawania 220 m/min)\n...toczenie...\nG97 S1500          (powrót do stałych obrotów)", caption: "W Sinumerik ograniczenie zapisuje się jako `LIMS=3000`." },
    { t: "note", kind: "warn", x: "**G96 bez ograniczenia obrotów jest niebezpieczne.** Gdy narzędzie zbliża się do osi obrotu, wyliczone obroty rosną do nieskończoności — sterownik podnosi je aż do maksimum maszyny. Przy niewyważonym detalu albo uchwycie szczękowym pracującym poza zakresem kończy się to wyrwaniem detalu z uchwytu." },
    { t: "h", x: "Kiedy G97 jest konieczne" },
    { t: "ul", items: [
      "**Gwintowanie** (G32, G33, G76) — skok gwintu wynika ze sprzężenia posuwu z obrotami; zmienne obroty zniekształciłyby gwint.",
      "**Wiercenie w osi** — wiertło pracuje na stałej średnicy niezależnie od pozycji Z, a przy G96 sterownik liczyłby obroty ze współrzędnej X równej zeru.",
      "**Rowkowanie i przecinanie w pobliżu osi** — obroty rosłyby lawinowo.",
      "**Detale niewyważone, mimośrodowe, w uchwycie szczękowym** — bezpieczniej trzymać stałe, umiarkowane obroty.",
    ] },
    { t: "h", x: "Przykład" },
    { t: "sim", src: "G21 G90 G18 G95\nG50 S3000\nG97 S1500 M03\nG00 X62 Z2\nG96 S220\nG01 X0 Z0 F0.15\nG00 X60 Z2\nG01 X40 F0.3\nG01 Z-30\nG01 X62\nG00 Z2\nG97 S1500\nM30", caption: "Planowanie czoła do osi przy stałej Vc, następnie toczenie wzdłużne, na końcu powrót do stałych obrotów przed odjazdem. Panel stanu pokazuje aktualną pozycję średnicową." },
    { t: "h", x: "Dobór prędkości skrawania" },
    { t: "table", head: ["Materiał", "Vc dla węglika [m/min]", "Uwagi"], rows: [
      ["Aluminium", "300–1000", "Ograniczeniem są zwykle obroty maszyny, nie materiał"],
      ["Stal konstrukcyjna (S235, C45)", "150–300", "Najszerszy zakres zastosowań"],
      ["Stal stopowa ulepszana", "100–200", "Niższe wartości przy większej twardości"],
      ["Stal nierdzewna austenityczna", "80–160", "Skłonność do umocnienia — nie schodź poniżej zakresu"],
      ["Żeliwo szare", "150–350", "Wiór kruchy, mała siła skrawania"],
      ["Tytan", "30–70", "Niska przewodność cieplna, ciepło zostaje w ostrzu"],
      ["Stopy niklu (Inconel)", "20–50", "Wymaga obfitego chłodzenia"],
    ], caption: "Wartości orientacyjne dla płytek z węglika z powłoką. Zawsze weryfikuj z katalogiem producenta narzędzia dla konkretnego gatunku i geometrii." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak G50 / LIMS** przed G96.",
      "**Pozostawienie G96 przed wierceniem w osi** — alarm albo maksymalne obroty.",
      "**Wpisanie obrotów zamiast Vc** — `G96 S1500` to polecenie utrzymania 1500 m/min, czyli zawsze maksymalne obroty maszyny.",
      "**Brak powrotu do G97** przed odjazdem i zatrzymaniem — kolejna operacja startuje w nieoczekiwanym trybie.",
    ] },
  ],

  "g94-g95": [
    { t: "p", x: "**G94** i **G95** określają jednostkę posuwu. Przy **G94** adres F oznacza **milimetry na minutę**, przy **G95** — **milimetry na obrót wrzeciona**. To jedna z najczęstszych przyczyn kosztownych pomyłek, bo ta sama liczba znaczy w obu trybach coś skrajnie innego." },
    { t: "h", x: "Który tryb gdzie" },
    { t: "table", head: ["Maszyna", "Domyślny tryb", "Typowe wartości F"], rows: [
      ["Frezarka, centrum obróbkowe", "**G94** (mm/min)", "100–5000"],
      ["Tokarka", "**G95** (mm/obr)", "0,05–0,5"],
    ] },
    { t: "p", x: "Posuw na obrót jest wygodniejszy przy toczeniu, bo bezpośrednio odpowiada za grubość wióra i chropowatość: przy promieniu naroża płytki rε chropowatość teoretyczna wynosi w przybliżeniu **Rz ≈ f² / (8 · rε) · 1000** [µm]. Posuw minutowy jest naturalny przy frezowaniu, gdzie liczba ostrzy i obroty ustalają go pośrednio." },
    { t: "h", x: "Przeliczanie" },
    { t: "p", x: "Zależność jest prosta: **Vf [mm/min] = f [mm/obr] × n [obr/min]**. Posuw 0,25 mm/obr przy 1200 obr/min to 300 mm/min. Przy frezowaniu dochodzi liczba ostrzy: **Vf = fz × z × n**." },
    { t: "note", kind: "warn", x: "Uwaga na tokarki Fanuc starszych serii: tam jednostkę posuwu przełącza się kodami **G98 (mm/min)** i **G99 (mm/obr)** — czyli tymi samymi liczbami, które na frezarce oznaczają sposób powrotu w cyklach wiertarskich. Przenosząc kod między maszynami, sprawdź w instrukcji, która konwencja obowiązuje." },
    { t: "sim", src: "G21 G90 G18 G95\nG97 S1200 M03\nG00 X52 Z2\nG01 X44 F0.25\nG01 Z-35\nG01 X52\nG00 Z2\nM30", caption: "Toczenie z posuwem 0,25 mm/obr. Przy 1200 obr/min odpowiada to 300 mm/min." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**F0.2 na frezarce w G94** — posuw 0,2 mm/min, narzędzie stoi w miejscu i wypala się w materiale.",
      "**F250 na tokarce w G95** — 250 mm na obrót, natychmiastowe zniszczenie płytki lub wyrwanie detalu.",
      "**Zmiana trybu bez zmiany F** — przełączenie G94 na G95 przy F400 daje 400 mm/obr.",
    ] },
  ],

  "g54-g59": [
    { t: "p", x: "**G54–G59** wybierają jeden z sześciu **układów współrzędnych detalu**. W każdym z nich sterownik przechowuje wektor od zera maszyny (punktu referencyjnego) do zera detalu. Dzięki temu program pisze się w wygodnym układzie związanym z detalem, a nie w układzie maszyny." },
    { t: "h", x: "Trzy poziomy odniesienia" },
    { t: "ol", items: [
      "**Zero maszyny** — punkt stały, ustalany przy bazowaniu osi. Nie zmienia się.",
      "**Zero detalu** — punkt wybrany przez programistę na detalu; jego położenie względem zera maszyny zapisuje się w rejestrze G54–G59.",
      "**Zero programu** — zwykle tożsame z zerem detalu; wszystkie współrzędne w programie odnoszą się do niego.",
    ] },
    { t: "h", x: "Gdzie postawić zero detalu" },
    { t: "ul", items: [
      "**Frezowanie, detal prostokątny** — najczęściej lewy dolny narożnik, Z na górnej powierzchni. Wszystkie wymiary w XY są wtedy dodatnie, a głębokości ujemne.",
      "**Detal symetryczny** — środek. Upraszcza program i pozwala wykorzystać symetrię lustrzaną.",
      "**Toczenie** — oś obrotu (X0 to zawsze oś) i czoło gotowego detalu jako Z0. Ustawianie Z0 na czole surowym utrudnia korektę naddatku.",
      "**Odlewy i odkuwki** — punkt wyznaczony przez bazy technologiczne, nie przez krawędź surową.",
    ] },
    { t: "h", x: "Wiele zamocowań" },
    { t: "p", x: "Sześć rejestrów pozwala obrabiać kilka detali bez zmiany programu. Wystarczy zapisać obróbkę jednej sztuki w podprogramie i wywołać go dla każdego układu:" },
    { t: "code", x: "G54\nM98 P1001\nG55\nM98 P1001\nG56\nM98 P1001\nM30", caption: "Trzy identyczne detale w trzech imadłach. Zmienia się wyłącznie rejestr układu współrzędnych." },
    { t: "note", kind: "info", x: "Jeżeli sześć układów to za mało, Fanuc udostępnia rozszerzenie **G54.1 P1** do **P48** (albo P300 w nowszych sterownikach). Sinumerik ma standardowo G54–G57 oraz zakres **G505–G599**." },
    { t: "sim", src: "G21 G90 G17 G54\nS2000 M03\nG00 X0 Y0 Z5\nG01 Z-2 F120\nG01 X30 F350\nG01 Y20\nG01 X0\nG01 Y0\nG00 Z5\nM30", caption: "Kontur zaprogramowany względem zera detalu. Zmiana rejestru z G54 na G55 przeniesie całą obróbkę w inne miejsce stołu bez modyfikacji ani jednego bloku." },
    { t: "h", x: "Powiązane funkcje" },
    { t: "table", head: ["Kod", "Działanie"], rows: [
      ["**G52**", "Tymczasowe przesunięcie układu lokalnego względem aktywnego G54–G59"],
      ["**G53**", "Jednorazowy ruch we współrzędnych maszynowych — do pozycji wymiany narzędzia, wyładunku"],
      ["**G92**", "Przypisanie aktualnej pozycji zadanych współrzędnych (metoda sprzed G54)"],
      ["**G10**", "Programowa zmiana zawartości rejestru — przydatna przy obróbce serii z korekcją"],
    ] },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Pusty rejestr** — układ pokrywa się z zerem maszyny, a pierwszy dojazd kończy się kolizją.",
      "**Brak jawnego G54 w programie** — obowiązuje układ pozostawiony przez poprzednią pracę.",
      "**Ustawienie zera na powierzchni surowej** przy nierównym naddatku — pierwsze przejście miejscami nie dotknie materiału, miejscami zbierze dwa razy za dużo.",
      "**Zmiana zamocowania bez ponownego ustawienia zera** — nawet ten sam detal w tym samym imadle potrafi przesunąć się o dziesiąte części milimetra.",
    ] },
  ],

  "g17-g19": [
    { t: "p", x: "**G17, G18 i G19** wybierają **płaszczyznę roboczą**. Wybór ten decyduje o trzech rzeczach: w jakiej płaszczyźnie wykonywane są łuki G02/G03, którą osią działa kompensacja promienia G41/G42 i wzdłuż której osi pracują cykle wiertarskie." },
    { t: "table", head: ["Kod", "Płaszczyzna", "Osie ruchu", "Adresy środka łuku", "Oś cykli"], rows: [
      ["**G17**", "XY", "X, Y", "I, J", "Z"],
      ["**G18**", "ZX", "Z, X", "K, I", "Y"],
      ["**G19**", "YZ", "Y, Z", "J, K", "X"],
    ] },
    { t: "p", x: "Domyślną płaszczyzną frezarki jest **G17**, tokarki — **G18**. Płaszczyzny inne niż domyślna przydają się przy obróbce na głowicy kątowej, na centrach wieloosiowych i przy frezowaniu łuków w ściance bocznej detalu." },
    { t: "note", kind: "tip", x: "Płaszczyznę warto wpisywać jawnie w bloku bezpiecznego startu, nawet jeżeli jest domyślna. Program przenoszony na inną maszynę albo uruchamiany po awarii nie może zakładać, w jakim stanie zostawił sterownik poprzedni operator." },
    { t: "sim", src: "G21 G90 G18 G95\nG97 S1000 M03\nG00 X52 Z2\nG01 X40 F0.25\nG01 Z-20\nG02 X50 Z-25 R5\nG01 Z-40\nG01 X52\nG00 Z2\nM30", caption: "Łuk w płaszczyźnie ZX na tokarce. Zwróć uwagę, że użyto adresu R — przy zapisie przez środek należałoby użyć liter I i K, nie I i J." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Adres J w płaszczyźnie G18** — alarm albo tor niezgodny z zamierzeniem.",
      "**Kompensacja promienia przy niewłaściwej płaszczyźnie** — odsunięcie następuje w innej osi.",
      "**Cykl wiertarski przy G18 na frezarce** — wiercenie odbywa się wzdłuż osi Y.",
    ] },
  ],

  "g20-g21": [
    { t: "p", x: "**G21** ustawia jednostki metryczne (milimetry), **G20** — calowe. Wybór dotyczy wszystkiego: współrzędnych, posuwu, promieni, wartości w rejestrach korekcji." },
    { t: "note", kind: "warn", x: "**Sinumerik używa zupełnie innych kodów: G70 to cale, G71 to milimetry.** Co gorsza, na tokarce Fanuc **G70 i G71 oznaczają cykle toczenia** — wykańczający i zgrubny. Ten sam zapis na dwóch sterownikach robi dwie kompletnie różne rzeczy. To jedna z najbardziej podchwytliwych różnic między systemami." },
    { t: "table", head: ["Znaczenie", "Fanuc", "Sinumerik"], rows: [
      ["Cale", "G20", "G70"],
      ["Milimetry", "G21", "G71"],
      ["Cykl zgrubny toczenia", "G71", "CYCLE95"],
      ["Cykl wykańczający toczenia", "G70", "CYCLE95 (parametr)"],
    ] },
    { t: "p", x: "Przeliczenie: 1 cal = 25,4 mm. Program w calach uruchomiony na maszynie w trybie metrycznym daje detal **25,4 raza mniejszy** niż zamierzony — albo, w drugą stronę, ruchy 25,4 raza za duże, zwykle poza zakres osi." },
    { t: "note", kind: "tip", x: "Zawsze wpisuj jednostki jawnie w pierwszym bloku programu. Sterownik pamięta ostatnio używane ustawienie, a Ty nie masz gwarancji, kto i co uruchamiał wcześniej." },
  ],

  "g71-g70": [
    { t: "p", x: "**G71** to cykl **zgrubnego toczenia wzdłużnego**. Podajesz kontur gotowego detalu i głębokość jednego przejścia, a sterownik sam generuje wszystkie przejścia zdejmujące naddatek, zostawiając zadany naddatek na wykańczanie. **G70** wykonuje potem jedno przejście po tym samym konturze na gotowo." },
    { t: "h", x: "Dlaczego warto" },
    { t: "p", x: "Ręczne rozpisanie toczenia zgrubnego wałka z ⌀60 na ⌀30 przy głębokości 2 mm to około 40 bloków, z których każdy trzeba przeliczyć. W cyklu G71 to cztery linie plus opis konturu. Zmiana naddatku albo głębokości przejścia sprowadza się do poprawienia jednej liczby." },
    { t: "h", x: "Składnia Fanuc" },
    { t: "code", x: "G71 U2.0 R1.0                    ; głębokość przejścia i wycofanie\nG71 P100 Q200 U0.5 W0.1 F0.3     ; zakres bloków konturu i naddatki\nN100 G00 X30                     ; pierwszy blok konturu — tylko ruch w X\nG01 Z-25 F0.2\nX40 Z-35\nZ-55\nX50\nN200 X62                         ; ostatni blok konturu\nG70 P100 Q200 F0.15              ; przejście wykańczające" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["**U** (blok 1)", "Głębokość skrawania jednego przejścia, promieniowo"],
      ["**R** (blok 1)", "Wycofanie narzędzia po każdym przejściu"],
      ["**P, Q**", "Numery pierwszego i ostatniego bloku opisu konturu"],
      ["**U** (blok 2)", "Naddatek na wykańczanie w osi X, **średnicowo**"],
      ["**W** (blok 2)", "Naddatek na wykańczanie w osi Z"],
      ["**F**", "Posuw zgrubny; w bloku G70 — posuw wykańczający"],
    ] },
    { t: "note", kind: "warn", x: "Blok wskazany przez **P musi zawierać wyłącznie ruch w osi X** — bez współrzędnej Z. Naruszenie tej zasady to najczęstsza przyczyna alarmu przy G71. Kontur musi też być **monotoniczny**: średnica może tylko rosnąć albo tylko maleć wzdłuż Z (typ I). Kontury z podcięciami wymagają typu II lub cyklu G73." },
    { t: "sim", src: "G21 G90 G18 G95\nG50 S2500\nG96 S200 M03\nG00 X62 Z2\nG01 X56 F0.3\nG01 Z-55\nG00 X64\nG00 Z2\nG01 X50\nG01 Z-55\nG00 X64\nG00 Z2\nG01 X44\nG01 Z-35\nG01 X50 Z-45\nG00 X64\nG00 Z2\nG01 X38\nG01 Z-25\nG01 X44 Z-30\nG00 X64\nG00 Z2\nM30", caption: "Rozpisane ręcznie przejścia zgrubne — dokładnie to, co cykl G71 generuje wewnętrznie. Widać, jak kolejne przejścia stopniowo odsłaniają zarys stopnia." },
    { t: "h", x: "Pozostałe cykle tokarskie" },
    { t: "table", head: ["Kod", "Cykl", "Zastosowanie"], rows: [
      ["**G70**", "Wykańczanie po konturze P–Q", "Ostatnie przejście na wymiar"],
      ["**G71**", "Zgrubne toczenie wzdłużne", "Wałki, zdejmowanie naddatku wzdłuż osi"],
      ["**G72**", "Zgrubne toczenie poprzeczne", "Tarcze, planowanie dużych czół"],
      ["**G73**", "Powtarzanie konturu z przesunięciem", "Odkuwki i odlewy o kształcie zbliżonym do gotowego"],
      ["**G74**", "Wiercenie z przerwami (wzdłuż Z)", "Otwory głębokie w osi"],
      ["**G75**", "Rowkowanie (wzdłuż X)", "Rowki na pierścienie osadcze, podcięcia"],
      ["**G76**", "Gwintowanie wieloprzejściowe", "Gwinty zewnętrzne i wewnętrzne"],
    ] },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "Odpowiednikiem G71/G70 jest **CYCLE95**, w którym kontur zapisuje się w osobnym podprogramie, a parametry (naddatki, głębokość, rodzaj obróbki) przekazuje w wywołaniu. Rowkowanie realizują CYCLE93–95, gwintowanie — CYCLE97 i CYCLE99." },
  ],

  g76: [
    { t: "p", x: "**G76** wykonuje **kompletny gwint w jednym cyklu**: sterownik sam dzieli głębokość gwintu na kolejne przejścia o malejącym przyroście, prowadzi narzędzie zsynchronizowane z obrotami wrzeciona i wykonuje przejścia wykańczające." },
    { t: "h", x: "Dlaczego przejścia mają malejącą głębokość" },
    { t: "p", x: "Gdyby każde przejście schodziło o tyle samo, przekrój wióra rósłby z każdym przejściem — bo trójkątny zarys gwintu jest coraz szerszy przy większej głębokości. Cykl dobiera przyrosty tak, aby **pole przekroju wióra pozostawało w przybliżeniu stałe**: pierwsze przejście jest najgłębsze, kolejne coraz płytsze." },
    { t: "h", x: "Składnia Fanuc (dwa bloki)" },
    { t: "code", x: "G76 P010060 Q100 R0.05\nG76 X_ Z_ P_ Q_ F_" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["**P** (blok 1)", "Sześć cyfr w trzech parach: liczba przejść wykańczających (01), długość wybiegu w dziesiątych skoku (00), kąt zarysu w stopniach (60)"],
      ["**Q** (blok 1)", "Minimalna głębokość przejścia w mikrometrach"],
      ["**R** (blok 1)", "Naddatek na przejścia wykańczające"],
      ["**X, Z** (blok 2)", "Średnica dna gwintu i koniec gwintu"],
      ["**P** (blok 2)", "Wysokość gwintu w mikrometrach, promieniowo"],
      ["**Q** (blok 2)", "Głębokość pierwszego przejścia w mikrometrach"],
      ["**F**", "Skok gwintu"],
    ] },
    { t: "note", kind: "info", x: "Zapis `P010060` bywa mylący, bo wygląda jak jedna liczba. To skleja trzy niezależne parametry — jeden z najbardziej nieintuicyjnych fragmentów składni Fanuc." },
    { t: "h", x: "Obliczenia dla gwintu metrycznego" },
    { t: "p", x: "Dla gwintu zewnętrznego o skoku P wysokość zarysu wynosi w praktyce **h ≈ 0,613 × P**, a średnica dna **d₃ ≈ d − 1,227 × P**. Dla M24×3: h ≈ 1,84 mm (czyli P1840 w składni cyklu), średnica dna ≈ 20,3 mm. Średnicę zewnętrzną przed gwintowaniem toczy się zwykle o 0,1–0,2 mm mniejszą od nominalnej, żeby wierzchołki nie wychodziły ostre." },
    { t: "h", x: "Rozbieg i wybieg" },
    { t: "p", x: "Narzędzie musi osiągnąć synchronizację z wrzecionem, zanim dotknie materiału. Punkt startu w osi Z powinien leżeć **co najmniej dwa skoki przed początkiem gwintu**; przy dużych skokach i wysokich obrotach nawet cztery. Wybieg na końcu (druga para cyfr w P) pozwala płynnie wyprowadzić ostrze bez uskoku." },
    { t: "sim", src: "G21 G90 G18\nG97 S700 M03\nG00 X26 Z5\nG00 X23.2\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nG00 X22.6\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nG00 X22.1\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nM30", caption: "Trzy przejścia gwintu M24×1,5 rozpisane ręcznie, o malejącym przyroście głębokości — odpowiednik tego, co robi cykl G76." },
    { t: "note", kind: "warn", x: "Gwintowanie zawsze przy **G97** (stałe obroty). Przy G96 obroty zmieniałyby się wraz ze średnicą, a razem z nimi rzeczywisty skok gwintu." },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "Odpowiednikiem jest **CYCLE97** z parametrami podawanymi opisowo (skok, głębokość, liczba przejść, kąt, wybieg). Pojedyncze przejście gwintu realizuje **G33** z adresem `K` określającym skok." },
  ],

  "m03-m05": [
    { t: "p", x: "**M03** uruchamia wrzeciono w prawo, **M04** w lewo, **M05** je zatrzymuje. Prędkość obrotowa wynika z adresu **S** — obowiązującego modalnie, więc raz podana obowiązuje aż do zmiany." },
    { t: "h", x: "Który kierunek" },
    { t: "p", x: "Kierunek określa się **patrząc od strony wrzeciona w stronę narzędzia**. M03 to obrót zgodny z ruchem wskazówek zegara — kierunek właściwy dla zdecydowanej większości narzędzi prawotnących: frezów, wierteł, gwintowników prawych i standardowych noży tokarskich." },
    { t: "ul", items: [
      "**M04 na frezarce** — gwintowniki lewe, frezy lewotnące, wykręcanie gwintownika w cyklu G84.",
      "**M04 na tokarce** — noże lewe, obróbka od strony wrzeciona, narzędzia napędzane w konfiguracji odwrotnej.",
    ] },
    { t: "note", kind: "warn", x: "Zły kierunek obrotów oznacza, że ostrze pracuje powierzchnią przyłożenia zamiast natarcia. Narzędzie nie skrawa — gniecie materiał, grzeje się i najczęściej wykrusza w ciągu kilku sekund." },
    { t: "h", x: "Kolejność w bloku" },
    { t: "p", x: "Adres S może stać w tym samym bloku co M03 albo wcześniej. Ważne, żeby obroty były zadane **przed** pierwszym ruchem roboczym. Wiele sterowników czeka na osiągnięcie zadanych obrotów przed wykonaniem następnego bloku, ale nie wszystkie — przy dużych wrzecionach warto dodać krótki postój `G04 P500`." },
    { t: "sim", src: "G21 G90 G17 G54\nT1 M06\nS2400 M03\nG43 H1 Z50\nG00 X10 Y10\nG00 Z2\nM08\nG01 Z-3 F120\nG01 X70 F400\nG01 Y40\nG00 Z50\nM09\nM05\nM30", caption: "Standardowa sekwencja: narzędzie, obroty, korekcja długości, dojazd, chłodziwo, obróbka, odjazd, wyłączenie." },
    { t: "note", kind: "info", x: "**Tylko jedna funkcja M w bloku** — to ograniczenie większości sterowników Fanuc. Zapis `M03 M08` w jednej linii kończy się alarmem albo wykonaniem tylko jednej z funkcji. Sinumerik dopuszcza kilka M w bloku, ale trzymanie się reguły „jedno M na linię” zapewnia przenośność programu." },
  ],
};
