import type { Block } from "@/lib/article";

export const part3: Record<string, Block[]> = {
  "g96-g97": [
    { t: "p", x: "**G96** i **G97** decydują, co oznacza liczba przy adresie **S**. Przy **G97** jest to bezpośrednio prędkość obrotowa wrzeciona w obr/min. Przy **G96** — **prędkość skrawania w m/min**, a obroty sterownik przelicza sam, na bieżąco, w zależności od aktualnej średnicy toczenia." },
    { t: "h", x: "Dlaczego to ma znaczenie" },
    { t: "p", x: "Prędkość skrawania — czyli prędkość, z jaką materiał przesuwa się względem ostrza — zależy od średnicy: **Vc = π · D · n / 1000**. Podczas toczenia poprzecznego (planowania czoła) średnica maleje od zewnątrz do osi. Przy stałych obrotach prędkość skrawania spada wtedy proporcjonalnie i w pobliżu osi dochodzi do zera: ostrze przestaje skrawać, zaczyna gnieść materiał, powierzchnia się psuje, a płytka wykrusza." },
    { t: "p", x: "**G96 utrzymuje Vc na stałym poziomie**, podnosząc obroty w miarę zmniejszania średnicy. Efekt: równa chropowatość na całej powierzchni czoła i przewidywalna trwałość ostrza." },
    { t: "diagram", id: "g96-g97" },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G50 S3000          (Fanuc: ograniczenie obrotów — obowiązkowe przed G96)\nG96 S220 M03       (stała prędkość skrawania 220 m/min)\n...toczenie...\nG97 S1500          (powrót do stałych obrotów)", caption: "W Sinumerik ograniczenie zapisuje się jako `LIMS=3000`." },
    { t: "note", kind: "warn", x: "**G96 bez ograniczenia obrotów jest niebezpieczne.** Gdy narzędzie zbliża się do osi obrotu, wyliczone obroty rosną do nieskończoności — sterownik podnosi je aż do maksimum maszyny. Przy niewyważonym detalu albo uchwycie szczękowym pracującym poza zakresem kończy się to wyrwaniem detalu z uchwytu." },
    { t: "h", x: "Kiedy G97 jest konieczne" },
    { t: "ul", items: [
      "**Gwintowanie** (G32, G33, G76) — skok gwintu wynika ze sprzężenia posuwu z obrotami; zmienne obroty zniekształciłyby gwint.",
      "**Wiercenie w osi** — wiertło pracuje na stałej średnicy niezależnie od pozycji Z, a przy G96 sterownik liczyłby obroty ze współrzędnej X równej zeru.",
      "**Rowkowanie i przecinanie w pobliżu osi** — obroty rosłyby lawinowo.",
      "**Detale niewyważone, mimośrodowe, w uchwycie szczękowym** — bezpieczniej trzymać stałe, umiarkowane obroty.",
    ] },
    { t: "h", x: "Przykład" },
    { t: "sim", src: "G18 G21 G40 G99\nG50 S3000\nG97 S1500 M03\nG00 X62 Z2\nG96 S220\nG01 X0 Z0 F0.15\nG00 X60 Z2\nG01 X40 F0.3\nG01 Z-30\nG01 X62\nG00 Z2\nG97 S1500\nM30", caption: "Planowanie czoła do osi przy stałej Vc, następnie toczenie wzdłużne, na końcu powrót do stałych obrotów przed odjazdem. Panel stanu pokazuje aktualną pozycję średnicową." },
    { t: "h", x: "Dobór prędkości skrawania" },
    { t: "table", head: ["Materiał", "Vc dla węglika [m/min]", "Uwagi"], rows: [
      ["Aluminium", "300–1000", "Ograniczeniem są zwykle obroty maszyny, nie materiał"],
      ["Stal konstrukcyjna (S235, C45)", "150–300", "Najszerszy zakres zastosowań"],
      ["Stal stopowa ulepszana", "100–200", "Niższe wartości przy większej twardości"],
      ["Stal nierdzewna austenityczna", "80–160", "Skłonność do umocnienia — nie schodź poniżej zakresu"],
      ["Żeliwo szare", "150–350", "Wiór kruchy, mała siła skrawania"],
      ["Tytan", "30–70", "Niska przewodność cieplna, ciepło zostaje w ostrzu"],
      ["Stopy niklu (Inconel)", "20–50", "Wymaga obfitego chłodzenia"],
    ], caption: "Wartości orientacyjne dla płytek z węglika z powłoką. Zawsze weryfikuj z katalogiem producenta narzędzia dla konkretnego gatunku i geometrii." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak G50 / LIMS** przed G96.",
      "**Pozostawienie G96 przed wierceniem w osi** — alarm albo maksymalne obroty.",
      "**Wpisanie obrotów zamiast Vc** — `G96 S1500` to polecenie utrzymania 1500 m/min, czyli zawsze maksymalne obroty maszyny.",
      "**Brak powrotu do G97** przed odjazdem i zatrzymaniem — kolejna operacja startuje w nieoczekiwanym trybie.",
    ] },
  ],

  "g71-g70": [
    { t: "p", x: "**G71** to cykl **zgrubnego toczenia wzdłużnego**. Podajesz kontur gotowego detalu i głębokość jednego przejścia, a sterownik sam generuje wszystkie przejścia zdejmujące naddatek, zostawiając zadany naddatek na wykańczanie. **G70** wykonuje potem jedno przejście po tym samym konturze na gotowo." },
    { t: "h", x: "Dlaczego warto" },
    { t: "p", x: "Ręczne rozpisanie toczenia zgrubnego wałka z ⌀60 na ⌀30 przy głębokości 2 mm to około 40 bloków, z których każdy trzeba przeliczyć. W cyklu G71 to cztery linie plus opis konturu. Zmiana naddatku albo głębokości przejścia sprowadza się do poprawienia jednej liczby." },
    { t: "h", x: "Składnia Fanuc" },
    { t: "code", x: "G71 U2.0 R1.0                    ; głębokość przejścia i wycofanie\nG71 P100 Q200 U0.5 W0.1 F0.3     ; zakres bloków konturu i naddatki\nN100 G00 X30                     ; pierwszy blok konturu — tylko ruch w X\nG01 Z-25 F0.2\nX40 Z-35\nZ-55\nX50\nN200 X62                         ; ostatni blok konturu\nG70 P100 Q200 F0.15              ; przejście wykańczające" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["**U** (blok 1)", "Głębokość skrawania jednego przejścia, promieniowo"],
      ["**R** (blok 1)", "Wycofanie narzędzia po każdym przejściu"],
      ["**P, Q**", "Numery pierwszego i ostatniego bloku opisu konturu"],
      ["**U** (blok 2)", "Naddatek na wykańczanie w osi X, **średnicowo**"],
      ["**W** (blok 2)", "Naddatek na wykańczanie w osi Z"],
      ["**F**", "Posuw zgrubny; w bloku G70 — posuw wykańczający"],
    ] },
    { t: "note", kind: "warn", x: "Blok wskazany przez **P musi zawierać wyłącznie ruch w osi X** — bez współrzędnej Z. Naruszenie tej zasady to najczęstsza przyczyna alarmu przy G71. Kontur musi też być **monotoniczny**: średnica może tylko rosnąć albo tylko maleć wzdłuż Z (typ I). Kontury z podcięciami wymagają typu II lub cyklu G73." },
    { t: "sim", src: "G18 G21 G40 G99\nG50 S2500\nG96 S200 M03\nG00 X62 Z2\nG01 X56 F0.3\nG01 Z-55\nG00 X64\nG00 Z2\nG01 X50\nG01 Z-55\nG00 X64\nG00 Z2\nG01 X44\nG01 Z-35\nG01 X50 Z-45\nG00 X64\nG00 Z2\nG01 X38\nG01 Z-25\nG01 X44 Z-30\nG00 X64\nG00 Z2\nM30", caption: "Rozpisane ręcznie przejścia zgrubne — dokładnie to, co cykl G71 generuje wewnętrznie. Widać, jak kolejne przejścia stopniowo odsłaniają zarys stopnia." },
    { t: "h", x: "Pozostałe cykle tokarskie" },
    { t: "table", head: ["Kod", "Cykl", "Zastosowanie"], rows: [
      ["**G70**", "Wykańczanie po konturze P–Q", "Ostatnie przejście na wymiar"],
      ["**G71**", "Zgrubne toczenie wzdłużne", "Wałki, zdejmowanie naddatku wzdłuż osi"],
      ["**G72**", "Zgrubne toczenie poprzeczne", "Tarcze, planowanie dużych czół"],
      ["**G73**", "Powtarzanie konturu z przesunięciem", "Odkuwki i odlewy o kształcie zbliżonym do gotowego"],
      ["**G74**", "Wiercenie z przerwami (wzdłuż Z)", "Otwory głębokie w osi"],
      ["**G75**", "Rowkowanie (wzdłuż X)", "Rowki na pierścienie osadcze, podcięcia"],
      ["**G76**", "Gwintowanie wieloprzejściowe", "Gwinty zewnętrzne i wewnętrzne"],
    ] },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "Odpowiednikiem G71/G70 jest **CYCLE95**, w którym kontur zapisuje się w osobnym podprogramie, a parametry (naddatki, głębokość, rodzaj obróbki) przekazuje w wywołaniu. Rowkowanie realizują CYCLE93–95, gwintowanie — CYCLE97 i CYCLE99." },
  ],

  g76: [
    { t: "p", x: "**G76** wykonuje **kompletny gwint w jednym cyklu**: sterownik sam dzieli głębokość gwintu na kolejne przejścia o malejącym przyroście, prowadzi narzędzie zsynchronizowane z obrotami wrzeciona i wykonuje przejścia wykańczające." },
    { t: "h", x: "Dlaczego przejścia mają malejącą głębokość" },
    { t: "p", x: "Gdyby każde przejście schodziło o tyle samo, przekrój wióra rósłby z każdym przejściem — bo trójkątny zarys gwintu jest coraz szerszy przy większej głębokości. Cykl dobiera przyrosty tak, aby **pole przekroju wióra pozostawało w przybliżeniu stałe**: pierwsze przejście jest najgłębsze, kolejne coraz płytsze." },
    { t: "h", x: "Składnia Fanuc (dwa bloki)" },
    { t: "code", x: "G76 P010060 Q100 R0.05\nG76 X_ Z_ P_ Q_ F_" },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["**P** (blok 1)", "Sześć cyfr w trzech parach: liczba przejść wykańczających (01), długość wybiegu w dziesiątych skoku (00), kąt zarysu w stopniach (60)"],
      ["**Q** (blok 1)", "Minimalna głębokość przejścia w mikrometrach"],
      ["**R** (blok 1)", "Naddatek na przejścia wykańczające"],
      ["**X, Z** (blok 2)", "Średnica dna gwintu i koniec gwintu"],
      ["**P** (blok 2)", "Wysokość gwintu w mikrometrach, promieniowo"],
      ["**Q** (blok 2)", "Głębokość pierwszego przejścia w mikrometrach"],
      ["**F**", "Skok gwintu"],
    ] },
    { t: "note", kind: "info", x: "Zapis `P010060` bywa mylący, bo wygląda jak jedna liczba. To skleja trzy niezależne parametry — jeden z najbardziej nieintuicyjnych fragmentów składni Fanuc." },
    { t: "h", x: "Obliczenia dla gwintu metrycznego" },
    { t: "p", x: "Dla gwintu zewnętrznego o skoku P wysokość zarysu wynosi w praktyce **h ≈ 0,613 × P**, a średnica dna **d₃ ≈ d − 1,227 × P**. Dla M24×3: h ≈ 1,84 mm (czyli P1840 w składni cyklu), średnica dna ≈ 20,3 mm. Średnicę zewnętrzną przed gwintowaniem toczy się zwykle o 0,1–0,2 mm mniejszą od nominalnej, żeby wierzchołki nie wychodziły ostre." },
    { t: "h", x: "Rozbieg i wybieg" },
    { t: "p", x: "Narzędzie musi osiągnąć synchronizację z wrzecionem, zanim dotknie materiału. Punkt startu w osi Z powinien leżeć **co najmniej dwa skoki przed początkiem gwintu**; przy dużych skokach i wysokich obrotach nawet cztery. Wybieg na końcu (druga para cyfr w P) pozwala płynnie wyprowadzić ostrze bez uskoku." },
    { t: "sim", mode: "lathe", src: "G18 G21 G40 G99\nG97 S700 M03\nG00 X26 Z5\nG00 X23.2\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nG00 X22.6\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nG00 X22.1\nG01 Z-25 F1.5\nG00 X30\nG00 Z5\nM30", caption: "Trzy przejścia gwintu M24×1,5 rozpisane ręcznie, o malejącym przyroście głębokości — odpowiednik tego, co robi cykl G76." },
    { t: "note", kind: "warn", x: "Gwintowanie zawsze przy **G97** (stałe obroty). Przy G96 obroty zmieniałyby się wraz ze średnicą, a razem z nimi rzeczywisty skok gwintu." },
    { t: "h", x: "Sinumerik" },
    { t: "p", x: "Odpowiednikiem jest **CYCLE97** z parametrami podawanymi opisowo (skok, głębokość, liczba przejść, kąt, wybieg). Pojedyncze przejście gwintu realizuje **G33** z adresem `K` określającym skok." },
  ],

  "m03-m05": [
    { t: "p", x: "**M03** uruchamia wrzeciono w prawo, **M04** w lewo, **M05** je zatrzymuje. Prędkość obrotowa wynika z adresu **S** — obowiązującego modalnie, więc raz podana obowiązuje aż do zmiany." },
    { t: "h", x: "Który kierunek" },
    { t: "p", x: "Kierunek określa się **patrząc od strony wrzeciona w stronę narzędzia**. M03 to obrót zgodny z ruchem wskazówek zegara — kierunek właściwy dla zdecydowanej większości narzędzi prawotnących: frezów, wierteł, gwintowników prawych i standardowych noży tokarskich." },
    { t: "ul", items: [
      "**M04 na frezarce** — gwintowniki lewe, frezy lewotnące, wykręcanie gwintownika w cyklu G84.",
      "**M04 na tokarce** — noże lewe, obróbka od strony wrzeciona, narzędzia napędzane w konfiguracji odwrotnej.",
    ] },
    { t: "note", kind: "warn", x: "Zły kierunek obrotów oznacza, że ostrze pracuje powierzchnią przyłożenia zamiast natarcia. Narzędzie nie skrawa — gniecie materiał, grzeje się i najczęściej wykrusza w ciągu kilku sekund." },
    { t: "h", x: "Kolejność w bloku" },
    { t: "p", x: "Adres S może stać w tym samym bloku co M03 albo wcześniej. Ważne, żeby obroty były zadane **przed** pierwszym ruchem roboczym. Wiele sterowników czeka na osiągnięcie zadanych obrotów przed wykonaniem następnego bloku, ale nie wszystkie — przy dużych wrzecionach warto dodać krótki postój `G04 P500`." },
    { t: "sim", src: "G21 G90 G17 G54\nT1 M06\nS2400 M03\nG43 H1 Z50\nG00 X10 Y10\nG00 Z2\nM08\nG01 Z-3 F120\nG01 X70 F400\nG01 Y40\nG00 Z50\nM09\nM05\nM30", caption: "Standardowa sekwencja: narzędzie, obroty, korekcja długości, dojazd, chłodziwo, obróbka, odjazd, wyłączenie." },
    { t: "note", kind: "info", x: "**Tylko jedna funkcja M w bloku** — to ograniczenie większości sterowników Fanuc. Zapis `M03 M08` w jednej linii kończy się alarmem albo wykonaniem tylko jednej z funkcji. Sinumerik dopuszcza kilka M w bloku, ale trzymanie się reguły „jedno M na linię” zapewnia przenośność programu." },
  ],
};
