import type { Block } from "@/lib/article";

export const part2: Record<string, Block[]> = {
  "g81-g83": [
    { t: "p", x: "**Cykle stałe** zastępują kilkanaście bloków jednym. Zamiast pisać dojazd, zagłębienie, wycofanie i przejazd dla każdego otworu z osobna, definiujesz cykl raz, a potem podajesz same współrzędne kolejnych otworów. Sterownik powtarza w nich całą sekwencję." },
    { t: "h", x: "Anatomia cyklu wiercenia" },
    { t: "ol", items: [
      "Szybki przejazd do punktu X, Y.",
      "Szybki zjazd do **płaszczyzny R** — poziomu, od którego zaczyna się posuw roboczy, typowo 2–5 mm nad materiałem.",
      "Wiercenie z posuwem F do współrzędnej **Z** (dno otworu).",
      "Ewentualny postój na dnie albo wycofania z odprowadzeniem wióra.",
      "Powrót do płaszczyzny R (**G99**) albo do punktu początkowego (**G98**).",
    ] },
    { t: "diagram", id: "g81-g83" },
    { t: "h", x: "Najważniejsze cykle" },
    { t: "table", head: ["Kod", "Cykl", "Kiedy stosować"], rows: [
      ["**G81**", "Wiercenie proste — w dół i z powrotem", "Otwory płytkie, do 3× średnicy"],
      ["**G82**", "Wiercenie z postojem na dnie (adres P)", "Nawiercanie, pogłębianie czołowe — postój wygładza dno"],
      ["**G83**", "Wiercenie głębokie z **pełnym wycofaniem** co Q", "Otwory powyżej 3× średnicy, materiały z długim wiórem"],
      ["**G73**", "Wiercenie głębokie z **krótkim wycofaniem**", "Szybsze niż G83, ale gorzej usuwa wiór"],
      ["**G84**", "Gwintowanie gwintownikiem", "Posuw sprzężony z obrotami"],
      ["**G85**", "Wytaczanie z wyjściem na posuwie", "Otwory dokładne — brak śladu przy wyjściu"],
      ["**G80**", "Anulowanie cyklu", "Obowiązkowe po ostatnim otworze"],
    ] },
    { t: "h", x: "Składnia" },
    { t: "code", x: "G99 G81 X20 Y20 Z-15 R2 F120     (pierwszy otwór — cykl zdefiniowany i wykonany)\nX50                              (drugi otwór, te same parametry)\nX50 Y50                          (trzeci)\nX20 Y50                          (czwarty)\nG80                              (koniec cyklu)\nG00 Z50", caption: "Cztery otwory w pięciu blokach. Bez cyklu wymagałoby to około dwudziestu." },
    { t: "table", head: ["Adres", "Znaczenie"], rows: [
      ["X, Y", "Położenie otworu"],
      ["Z", "Współrzędna dna otworu (wartość ujemna względem zera detalu)"],
      ["R", "Płaszczyzna początku posuwu roboczego"],
      ["Q", "Głębokość jednego zagłębienia w G83 i G73"],
      ["P", "Czas postoju na dnie w milisekundach (G82, G89)"],
      ["F", "Posuw wiercenia"],
      ["K lub L", "Liczba powtórzeń — używane głównie z G91"],
    ] },
    { t: "h", x: "G98 kontra G99" },
    { t: "p", x: "Te dwie funkcje decydują, dokąd narzędzie wraca po każdym otworze. **G99** wraca tylko do płaszczyzny R — to szybsze, więc stosuje się je domyślnie. **G98** wraca do wysokości, na której narzędzie było przed rozpoczęciem cyklu — potrzebne, gdy między otworami znajduje się przeszkoda: zacisk, żebro odlewu, wcześniej obrobiony stopień." },
    { t: "note", kind: "tip", x: "Częsta praktyka: pracuj w G99, a przed otworem za przeszkodą wstaw pojedynczy blok z G98. Tryb jest modalny, więc pamiętaj o powrocie do G99 dla kolejnych otworów." },
    { t: "h", x: "Wiercenie głębokie" },
    { t: "p", x: "Powyżej trzech średnic wiór przestaje samodzielnie wychodzić z otworu — zaczyna się zakleszczać, rosną opory i temperatura. **G83** wycofuje wiertło **całkowicie do płaszczyzny R** po każdym zagłębieniu o Q, dzięki czemu wiór jest łamany i usuwany, a chłodziwo dociera do dna. Kosztem jest czas. **G73** wycofuje tylko o niewielką wartość (parametr maszynowy, zwykle 0,5–1 mm) — szybciej, ale wiór zostaje w otworze." },
    { t: "sim", src: "G21 G90 G17 G54\nS1200 M03\nG00 X20 Y20 Z10\nM08\nG01 Z-6 F100\nG00 Z2\nG01 Z-12 F100\nG00 Z2\nG01 Z-18 F100\nG00 Z10\nG00 X50 Y20\nG01 Z-6 F100\nG00 Z2\nG01 Z-12 F100\nG00 Z2\nG01 Z-18 F100\nG00 Z10\nM09\nM30", caption: "Ręcznie rozpisany odpowiednik cyklu G83 z Q6 dla dwóch otworów — dokładnie to, co sterownik robi wewnętrznie. Symulator nie interpretuje jeszcze cykli stałych, więc przykłady rozpisujemy jawnie." },
    { t: "h", x: "Sinumerik: cykle parametryczne" },
    { t: "p", x: "Sinumerik nie używa G81–G89, tylko wywołań z listą parametrów: `CYCLE81`, `CYCLE82`, `CYCLE83`, `CYCLE84` (gwintowanie), `CYCLE85`. Powtarzanie w kolejnych punktach realizuje modalne wywołanie `MCALL`:" },
    { t: "code", x: "MCALL CYCLE81(10, 0, 2, -15)   ; RTP, RFP, SDIS, DP\nX20 Y20\nX50 Y20\nX50 Y50\nMCALL                          ; wyłączenie wywołania modalnego", caption: "Odpowiednik cyklu G81 z czterema otworami w składni Sinumerik." },
    { t: "h", x: "Typowe błędy" },
    { t: "ul", items: [
      "**Brak G80 na końcu.** Kolejny blok ze współrzędnymi X Y — na przykład dojazd do frezowania — wykona jeszcze jeden otwór.",
      "**Płaszczyzna R poniżej powierzchni materiału.** Szybki zjazd do R oznacza wtedy wjazd wiertła w detal z prędkością szybką.",
      "**G99 przy zaciskach między otworami.** Klasyczna kolizja: narzędzie wraca tylko 2 mm nad materiał i uderza w zacisk.",
      "**Q większe od pozostałej głębokości** w ostatnim zagłębieniu — na części sterowników powoduje przekroczenie zadanego Z.",
      "**Cykl w trybie G91 bez przemyślenia** — Z i R liczone są wtedy przyrostowo, co daje zupełnie inne głębokości.",
    ] },
  ],
};
